// This file is auto-generated by @hey-api/openapi-ts

import type { V3CheckLoginResponse, V3GetUserSelfResponse, V3ExportUserDataResponse, V3GetUserByUserIdResponse, V3CreateCheckoutResponse, V3GetLeaderboardResponse, V3SearchWorkspacesResponse } from './types.gen';

const dtoUserPublicSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const checkLoginResponseSchemaResponseTransformer = (data: any) => {
    if (data.user) {
        data.user = dtoUserPublicSchemaResponseTransformer(data.user);
    }
    return data;
};

export const v3CheckLoginResponseTransformer = async (data: any): Promise<V3CheckLoginResponse> => {
    data = checkLoginResponseSchemaResponseTransformer(data);
    return data;
};

export const v3GetUserSelfResponseTransformer = async (data: any): Promise<V3GetUserSelfResponse> => {
    data = dtoUserPublicSchemaResponseTransformer(data);
    return data;
};

const dataExportResponseSchemaResponseTransformer = (data: any) => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const v3ExportUserDataResponseTransformer = async (data: any): Promise<V3ExportUserDataResponse> => {
    data = dataExportResponseSchemaResponseTransformer(data);
    return data;
};

export const v3GetUserByUserIdResponseTransformer = async (data: any): Promise<V3GetUserByUserIdResponse> => {
    data = dtoUserPublicSchemaResponseTransformer(data);
    return data;
};

const checkoutResponseSchemaResponseTransformer = (data: any) => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const v3CreateCheckoutResponseTransformer = async (data: any): Promise<V3CreateCheckoutResponse> => {
    data = checkoutResponseSchemaResponseTransformer(data);
    return data;
};

const srcDtoUserPublicSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const leaderboardEntrySchemaResponseTransformer = (data: any) => {
    data.user = srcDtoUserPublicSchemaResponseTransformer(data.user);
    return data;
};

const leaderboardResponseSchemaResponseTransformer = (data: any) => {
    data.entries = data.entries.map((item: any) => {
        return leaderboardEntrySchemaResponseTransformer(item);
    });
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const v3GetLeaderboardResponseTransformer = async (data: any): Promise<V3GetLeaderboardResponse> => {
    data = leaderboardResponseSchemaResponseTransformer(data);
    return data;
};

const workspaceSearchResultSchemaResponseTransformer = (data: any) => {
    if (data.recentActivity) {
        data.recentActivity = new Date(data.recentActivity);
    }
    return data;
};

const workspaceSearchResponseSchemaResponseTransformer = (data: any) => {
    data.results = data.results.map((item: any) => {
        return workspaceSearchResultSchemaResponseTransformer(item);
    });
    return data;
};

export const v3SearchWorkspacesResponseTransformer = async (data: any): Promise<V3SearchWorkspacesResponse> => {
    data = workspaceSearchResponseSchemaResponseTransformer(data);
    return data;
};