// This file is auto-generated by @hey-api/openapi-ts

export const TokenRefreshResponseSchema = {
    type: 'object',
    required: [
        'token',
        'tokenV1'
    ],
    properties: {
        token: {
            type: 'string'
        },
        tokenV1: {
            type: 'string'
        }
    }
} as const;

export const DiscountPublicSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'code',
        'amount',
        'amountType',
        'duration',
        'status'
    ],
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        amount: {
            type: 'integer'
        },
        amountType: {
            type: 'string',
            description: '"percent" or "fixed"'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        duration: {
            type: 'string',
            description: '"once", "repeating", or "forever"'
        },
        durationInMonths: {
            type: 'integer',
            nullable: true
        },
        status: {
            type: 'string',
            description: '"published" or "draft"'
        }
    }
} as const;

export const YearlyReportDataPublicSchema = {
    type: 'object',
    required: [
        'topLanguages',
        'hourlyDistribution',
        'dailyDistribution'
    ],
    properties: {
        topLanguages: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TopPublic'
            }
        },
        hourlyDistribution: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TopPublic'
            }
        },
        dailyDistribution: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TopPublic'
            }
        }
    }
} as const;

export const CheckoutRequestSchema = {
    type: 'object',
    required: [
        'type',
        'product'
    ],
    properties: {
        type: {
            type: 'string',
            enum: [
                'monthly',
                'yearly'
            ]
        },
        product: {
            type: 'string',
            enum: [
                'subscription',
                'onetime'
            ]
        },
        locale: {
            type: 'string'
        }
    }
} as const;

export const CheckoutResponseSchema = {
    type: 'object',
    required: [
        'checkoutUrl',
        'expiresAt'
    ],
    properties: {
        checkoutUrl: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const PricingPublicSchema = {
    type: 'object',
    required: [
        'currency',
        'subscriptionMonthly',
        'subscriptionYearly',
        'onetimeMonthly',
        'onetimeYearly',
        'annualDiscountPercent'
    ],
    properties: {
        currency: {
            type: 'string'
        },
        subscriptionMonthly: {
            type: 'integer',
            nullable: true,
            description: 'Price in cents'
        },
        subscriptionYearly: {
            type: 'integer',
            nullable: true,
            description: 'Price in cents'
        },
        onetimeMonthly: {
            type: 'integer',
            nullable: true,
            description: 'Price in cents'
        },
        onetimeYearly: {
            type: 'integer',
            nullable: true,
            description: 'Price in cents'
        },
        annualDiscountPercent: {
            type: 'integer',
            nullable: true,
            description: 'Yearly vs monthly×12 saving, in percent'
        }
    }
} as const;

export const ProductPublicSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'description',
        'price',
        'currency'
    ],
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        price: {
            type: 'integer',
            description: 'Price in cents'
        },
        currency: {
            type: 'string'
        },
        interval: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const WebhookResponseSchema = {
    type: 'object',
    required: [
        'success',
        'message'
    ],
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const LanguageRankingEntrySchema = {
    type: 'object',
    required: [
        'user',
        'totalMinutes',
        'rank',
        'percentile'
    ],
    properties: {
        user: {
            $ref: '#/components/schemas/UserPublic'
        },
        totalMinutes: {
            type: 'integer'
        },
        rank: {
            type: 'integer'
        },
        percentile: {
            type: 'number'
        }
    }
} as const;

export const LanguageRankingResponseSchema = {
    type: 'object',
    required: [
        'entries',
        'language',
        'totalUsers',
        'updatedAt'
    ],
    properties: {
        entries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/LanguageRankingEntry'
            }
        },
        language: {
            type: 'string'
        },
        totalUsers: {
            type: 'integer'
        },
        timeRangeDays: {
            type: 'integer',
            nullable: true
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const LeaderboardEntrySchema = {
    type: 'object',
    required: [
        'user',
        'totalMinutes',
        'rank'
    ],
    properties: {
        user: {
            $ref: '#/components/schemas/UserPublic'
        },
        totalMinutes: {
            type: 'integer'
        },
        rank: {
            type: 'integer'
        }
    }
} as const;

export const LeaderboardResponseSchema = {
    type: 'object',
    required: [
        'entries',
        'totalUsers',
        'updatedAt'
    ],
    properties: {
        entries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/LeaderboardEntry'
            }
        },
        totalUsers: {
            type: 'integer'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserCodingHistoryResponseSchema = {
    type: 'object',
    required: [
        'userId',
        'username',
        'totalMinutes',
        'data',
        'periodStart',
        'periodEnd',
        'timeRangeDays',
        'updatedAt'
    ],
    properties: {
        userId: {
            type: 'integer'
        },
        username: {
            type: 'string'
        },
        totalMinutes: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/StatsTimeData'
            }
        },
        periodStart: {
            type: 'string',
            format: 'date'
        },
        periodEnd: {
            type: 'string',
            format: 'date'
        },
        timeRangeDays: {
            type: 'integer'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserLanguageRankResponseSchema = {
    type: 'object',
    required: [
        'userId',
        'username',
        'language',
        'totalMinutes',
        'rank',
        'percentile',
        'totalUsers',
        'updatedAt'
    ],
    properties: {
        userId: {
            type: 'integer'
        },
        username: {
            type: 'string'
        },
        language: {
            type: 'string'
        },
        totalMinutes: {
            type: 'integer'
        },
        rank: {
            type: 'integer'
        },
        percentile: {
            type: 'number'
        },
        totalUsers: {
            type: 'integer'
        },
        timeRangeDays: {
            type: 'integer',
            nullable: true
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const StatsTimeDataSchema = {
    type: 'object',
    required: [
        'duration',
        'time'
    ],
    properties: {
        duration: {
            type: 'integer'
        },
        time: {
            type: 'string'
        }
    }
} as const;

export const TagHistoryResponseSchema = {
    type: 'object',
    required: [
        'tag',
        'data',
        'totalMinutes',
        'periodStart',
        'periodEnd'
    ],
    properties: {
        tag: {
            $ref: '#/components/schemas/TagResponse'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/StatsTimeData'
            }
        },
        totalMinutes: {
            type: 'integer'
        },
        periodStart: {
            type: 'string',
            format: 'date'
        },
        periodEnd: {
            type: 'string',
            format: 'date'
        }
    }
} as const;

export const WorkspaceEvaluationRequestSchema = {
    type: 'object',
    required: [
        'workspaceName',
        'language',
        'platform',
        'editor',
        'relativeFile'
    ],
    properties: {
        workspaceName: {
            type: 'string'
        },
        language: {
            type: 'string'
        },
        gitOrigin: {
            type: 'string',
            nullable: true
        },
        gitBranch: {
            type: 'string',
            nullable: true
        },
        platform: {
            type: 'string'
        },
        editor: {
            type: 'string'
        },
        absoluteFile: {
            type: 'string',
            nullable: true
        },
        relativeFile: {
            type: 'string'
        }
    }
} as const;

export const WorkspaceEvaluationResponseSchema = {
    type: 'object',
    required: [
        'matchingTags'
    ],
    properties: {
        matchingTags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TagResponse'
            }
        }
    }
} as const;

export const TagResponseSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'color',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        emoji: {
            type: 'string',
            nullable: true
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        rules: {
            type: 'object',
            nullable: true,
            additionalProperties: true
        }
    }
} as const;

export const TagCreateRequestSchema = {
    type: 'object',
    required: [
        'name',
        'color'
    ],
    properties: {
        name: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        emoji: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const TagUpdateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        color: {
            type: 'string',
            nullable: true
        },
        emoji: {
            type: 'string',
            nullable: true
        },
        rules: {
            type: 'object',
            nullable: true,
            additionalProperties: true
        }
    }
} as const;

export const TagTimeDataSchema = {
    type: 'object',
    required: [
        'tag',
        'totalMinutes'
    ],
    properties: {
        tag: {
            $ref: '#/components/schemas/TagResponse'
        },
        totalMinutes: {
            type: 'integer'
        }
    }
} as const;

export const TagTimeStatsResponseSchema = {
    type: 'object',
    required: [
        'data',
        'totalMinutes',
        'periodStart',
        'periodEnd'
    ],
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TagTimeData'
            }
        },
        totalMinutes: {
            type: 'integer'
        },
        periodStart: {
            type: 'string',
            format: 'date'
        },
        periodEnd: {
            type: 'string',
            format: 'date'
        }
    }
} as const;

export const UserPublicSchema = {
    type: 'object',
    required: [
        'id',
        'username',
        'plan',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            type: 'integer'
        },
        email: {
            type: 'string',
            nullable: true
        },
        username: {
            type: 'string'
        },
        avatar: {
            type: 'string',
            nullable: true
        },
        githubId: {
            type: 'integer',
            nullable: true
        },
        githubLogin: {
            type: 'string',
            nullable: true
        },
        bio: {
            type: 'string',
            nullable: true
        },
        googleId: {
            type: 'string',
            nullable: true
        },
        plan: {
            type: 'string'
        },
        timezone: {
            type: 'string',
            nullable: true
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const WidgetStatusResponseSchema = {
    type: 'object',
    required: [
        'username',
        'plan',
        'todayMinutes'
    ],
    properties: {
        username: {
            type: 'string'
        },
        plan: {
            type: 'string'
        },
        project: {
            type: 'string',
            nullable: true
        },
        language: {
            type: 'string',
            nullable: true
        },
        editor: {
            type: 'string',
            nullable: true
        },
        lastActiveAt: {
            type: 'integer',
            nullable: true,
            description: 'Unix seconds.'
        },
        todayMinutes: {
            type: 'integer'
        }
    }
} as const;

export const TopPublicSchema = {
    type: 'object',
    required: [
        'field',
        'minutes'
    ],
    properties: {
        field: {
            type: 'string'
        },
        minutes: {
            type: 'integer'
        }
    }
} as const;

export const WidgetTopLanguagesResponseSchema = {
    type: 'object',
    required: [
        'plan',
        'days',
        'limit',
        'capped',
        'items'
    ],
    properties: {
        plan: {
            type: 'string'
        },
        days: {
            type: 'integer'
        },
        limit: {
            type: 'integer'
        },
        capped: {
            type: 'boolean'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TopPublic'
            }
        }
    }
} as const;

export const WidgetTopProjectsResponseSchema = {
    type: 'object',
    required: [
        'plan',
        'days',
        'limit',
        'capped',
        'items'
    ],
    properties: {
        plan: {
            type: 'string'
        },
        days: {
            type: 'integer'
        },
        limit: {
            type: 'integer'
        },
        capped: {
            type: 'boolean'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TopPublic'
            }
        }
    }
} as const;

export const WidgetUsageResponseSchema = {
    type: 'object',
    required: [
        'plan',
        'range',
        'until',
        'tokens',
        'inputTokens',
        'cachedInputTokens',
        'outputTokens',
        'reasoningOutputTokens',
        'estimatedCostUsd'
    ],
    properties: {
        plan: {
            type: 'string'
        },
        range: {
            type: 'string',
            enum: []
        },
        since: {
            type: 'string',
            format: 'date-time',
            nullable: true,
            description: 'Inclusive lower bound; null when `range=all`.'
        },
        until: {
            type: 'string',
            format: 'date-time'
        },
        tokens: {
            type: 'integer'
        },
        inputTokens: {
            type: 'integer'
        },
        cachedInputTokens: {
            type: 'integer'
        },
        outputTokens: {
            type: 'integer'
        },
        reasoningOutputTokens: {
            type: 'integer'
        },
        estimatedCostUsd: {
            type: 'number'
        }
    }
} as const;

export const EventLogRequestSchema = {
    type: 'object',
    required: [
        'eventTime',
        'language',
        'project',
        'relativeFile',
        'editor',
        'platform'
    ],
    properties: {
        eventTime: {
            type: 'integer'
        },
        language: {
            type: 'string'
        },
        project: {
            type: 'string'
        },
        relativeFile: {
            type: 'string'
        },
        editor: {
            type: 'string'
        },
        platform: {
            type: 'string'
        },
        absoluteFile: {
            type: 'string',
            nullable: true
        },
        gitOrigin: {
            type: 'string',
            nullable: true
        },
        gitBranch: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const PyErrorSchema = {
    type: 'object',
    required: [
        'status_code',
        'detail'
    ],
    properties: {
        status_code: {
            type: 'integer'
        },
        detail: {
            type: 'string'
        }
    }
} as const;

export const UserSelfPublicSchema = {
    type: 'object',
    required: [
        'id',
        'username',
        'plan',
        'uploadToken',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            type: 'integer'
        },
        email: {
            type: 'string',
            nullable: true
        },
        username: {
            type: 'string'
        },
        avatar: {
            type: 'string',
            nullable: true
        },
        githubId: {
            type: 'integer',
            nullable: true
        },
        githubLogin: {
            type: 'string',
            nullable: true
        },
        bio: {
            type: 'string',
            nullable: true
        },
        googleId: {
            type: 'string',
            nullable: true
        },
        appleId: {
            type: 'string',
            nullable: true
        },
        plan: {
            type: 'string'
        },
        timezone: {
            type: 'string',
            nullable: true
        },
        uploadToken: {
            type: 'string'
        },
        planExpiresAt: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        planStatus: {
            type: 'string',
            nullable: true
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserDeleteResponseSchema = {
    type: 'object',
    required: [
        'success',
        'message'
    ],
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const EventLogPublicSchema = {
    type: 'object',
    required: [
        'eventTime',
        'language',
        'project',
        'relativeFile',
        'editor',
        'platform',
        'absoluteFile',
        'gitOrigin',
        'gitBranch'
    ],
    properties: {
        eventTime: {
            type: 'integer'
        },
        language: {
            type: 'string'
        },
        project: {
            type: 'string'
        },
        relativeFile: {
            type: 'string'
        },
        editor: {
            type: 'string'
        },
        platform: {
            type: 'string'
        },
        absoluteFile: {
            type: 'string'
        },
        gitOrigin: {
            type: 'string'
        },
        gitBranch: {
            type: 'string'
        }
    }
} as const;

export const SimpleMinutesSchema = {
    type: 'object',
    required: [
        'minutes'
    ],
    properties: {
        minutes: {
            type: 'integer'
        }
    }
} as const;

export const UserOverallRankResponseSchema = {
    type: 'object',
    required: [
        'userId',
        'username',
        'updatedAt'
    ],
    properties: {
        userId: {
            type: 'integer'
        },
        username: {
            type: 'string'
        },
        totalMinutes: {
            type: 'integer',
            nullable: true
        },
        percentile: {
            type: 'number',
            nullable: true
        },
        timeRangeDays: {
            type: 'integer',
            nullable: true
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const FacetSchema = {
    type: 'string',
    enum: [
        'public',
        'private'
    ]
} as const;

export const PrivacySettingsSchema = {
    type: 'object',
    required: [
        'v',
        'profilePublic',
        'widgetsEnabled',
        'leaderboardListed',
        'identity',
        'status',
        'history'
    ],
    properties: {
        v: {
            type: 'integer'
        },
        profilePublic: {
            type: 'boolean'
        },
        widgetsEnabled: {
            type: 'boolean'
        },
        leaderboardListed: {
            type: 'boolean'
        },
        identity: {
            type: 'object',
            required: [
                'email',
                'github'
            ],
            properties: {
                email: {
                    $ref: '#/components/schemas/Facet'
                },
                github: {
                    $ref: '#/components/schemas/Facet'
                }
            }
        },
        status: {
            type: 'object',
            required: [
                'coding',
                'project',
                'language',
                'editor'
            ],
            properties: {
                coding: {
                    $ref: '#/components/schemas/Facet'
                },
                project: {
                    $ref: '#/components/schemas/Facet'
                },
                language: {
                    $ref: '#/components/schemas/Facet'
                },
                editor: {
                    $ref: '#/components/schemas/Facet'
                }
            }
        },
        history: {
            type: 'object',
            required: [
                'totalTime',
                'languages',
                'projects',
                'calendar'
            ],
            properties: {
                totalTime: {
                    $ref: '#/components/schemas/Facet'
                },
                languages: {
                    $ref: '#/components/schemas/Facet'
                },
                projects: {
                    $ref: '#/components/schemas/Facet'
                },
                calendar: {
                    $ref: '#/components/schemas/Facet'
                }
            }
        }
    }
} as const;

export const StatsTimeResponseSchema = {
    type: 'object',
    required: [
        'data'
    ],
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/StatsTimeData'
            }
        }
    }
} as const;

export const StatsDataSchema = {
    type: 'object',
    required: [
        'duration',
        'time',
        'by'
    ],
    properties: {
        duration: {
            type: 'integer'
        },
        time: {
            type: 'string'
        },
        by: {
            type: 'string'
        }
    }
} as const;

export const StatsResponseSchema = {
    type: 'object',
    required: [
        'data'
    ],
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/StatsData'
            }
        }
    }
} as const;

export const TimeDistributionDataSchema = {
    type: 'object',
    required: [
        'hour',
        'minute',
        'count'
    ],
    properties: {
        hour: {
            type: 'integer'
        },
        minute: {
            type: 'integer'
        },
        count: {
            type: 'integer'
        }
    }
} as const;

export const TimeDistributionResponseSchema = {
    type: 'object',
    required: [
        'data'
    ],
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TimeDistributionData'
            }
        }
    }
} as const;

export const UserTopLanguageRankEntrySchema = {
    type: 'object',
    required: [
        'language',
        'totalMinutes'
    ],
    properties: {
        language: {
            type: 'string'
        },
        totalMinutes: {
            type: 'integer'
        },
        percentile: {
            type: 'number',
            nullable: true
        }
    }
} as const;

export const UserTopLanguagesRankResponseSchema = {
    type: 'object',
    required: [
        'userId',
        'username',
        'entries',
        'updatedAt'
    ],
    properties: {
        userId: {
            type: 'integer'
        },
        username: {
            type: 'string'
        },
        entries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/UserTopLanguageRankEntry'
            }
        },
        timeRangeDays: {
            type: 'integer',
            nullable: true
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const WorkspaceFileActivitySchema = {
    type: 'object',
    required: [
        'language',
        'relativeFile',
        'gitBranch',
        'minutes'
    ],
    properties: {
        language: {
            type: 'string'
        },
        relativeFile: {
            type: 'string'
        },
        gitBranch: {
            type: 'string'
        },
        minutes: {
            type: 'integer'
        }
    }
} as const;

export const WorkspaceSearchResultSchema = {
    type: 'object',
    required: [
        'workspaceName'
    ],
    properties: {
        workspaceName: {
            type: 'string'
        }
    }
} as const;

export const WorkspaceSearchResponseSchema = {
    type: 'object',
    required: [
        'results',
        'totalResults'
    ],
    properties: {
        results: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WorkspaceSearchResult'
            }
        },
        totalResults: {
            type: 'integer'
        }
    }
} as const;

export const ShieldResponseSchema = {
    type: 'object',
    required: [
        'schemaVersion',
        'label',
        'message',
        'color'
    ],
    properties: {
        schemaVersion: {
            type: 'integer'
        },
        logoSvg: {
            type: 'string',
            nullable: true
        },
        label: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        labelColor: {
            type: 'string',
            nullable: true
        }
    }
} as const;
