// This file is auto-generated by @hey-api/openapi-ts

import type { GetV3AgentDashboardResponse, GetV3AgentProjectsResponse, GetV3AgentSessionsResponse, GetV3DiscountsActiveResponse, GetV3PublicLanguageRankingResponse, GetV3PublicLeaderboardResponse, GetV3PublicUsersByUserIdCodingHistoryResponse, GetV3PublicUsersByUserIdLanguageRankResponse, GetV3PublicUsersByUserIdOverallRankResponse, GetV3PublicUsersByUserIdTopLanguagesRankResponse, GetV3TagsByTagIdHistoryResponse, GetV3TagsByTagIdResponse, GetV3TagsResponse, GetV3TagsStatsResponse, GetV3TotalMinutesResponse, GetV3UsersByUserIdPublicUsageResponse, GetV3UsersByUserIdResponse, GetV3UsersSelfOverallRankResponse, GetV3UsersSelfResponse, GetV3UsersSelfTopLanguagesRankResponse, PostV3PaymentsCheckoutResponse, PostV3TagsEvaluateResponse, PostV3TagsResponse, PostV3UsersSelfBioResponse, PostV3UsersSelfDeleteChallengeResponse, PostV3UsersSelfUsernameResponse, PutV3TagsByTagIdResponse } from './types.gen';

export const getV3AgentDashboardResponseTransformer = async (data: any): Promise<GetV3AgentDashboardResponse> => {
    if (data.range.since) {
        data.range.since = new Date(data.range.since);
    }
    data.range.until = new Date(data.range.until);
    return data;
};

export const getV3AgentProjectsResponseTransformer = async (data: any): Promise<GetV3AgentProjectsResponse> => {
    data.results = data.results.map((item: any) => {
        item.lastEventAt = new Date(item.lastEventAt);
        return item;
    });
    return data;
};

export const getV3AgentSessionsResponseTransformer = async (data: any): Promise<GetV3AgentSessionsResponse> => {
    data.sessions = data.sessions.map((item: any) => {
        item.startedAt = new Date(item.startedAt);
        item.lastEventAt = new Date(item.lastEventAt);
        return item;
    });
    return data;
};

const discountPublicSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const getV3DiscountsActiveResponseTransformer = async (data: any): Promise<GetV3DiscountsActiveResponse> => {
    data = data.map((item: any) => discountPublicSchemaResponseTransformer(item));
    return data;
};

const checkoutResponseSchemaResponseTransformer = (data: any) => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const postV3PaymentsCheckoutResponseTransformer = async (data: any): Promise<PostV3PaymentsCheckoutResponse> => {
    data = checkoutResponseSchemaResponseTransformer(data);
    return data;
};

const userPublicSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const languageRankingEntrySchemaResponseTransformer = (data: any) => {
    data.user = userPublicSchemaResponseTransformer(data.user);
    return data;
};

const languageRankingResponseSchemaResponseTransformer = (data: any) => {
    data.entries = data.entries.map((item: any) => languageRankingEntrySchemaResponseTransformer(item));
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3PublicLanguageRankingResponseTransformer = async (data: any): Promise<GetV3PublicLanguageRankingResponse> => {
    data = languageRankingResponseSchemaResponseTransformer(data);
    return data;
};

const leaderboardEntrySchemaResponseTransformer = (data: any) => {
    data.user = userPublicSchemaResponseTransformer(data.user);
    return data;
};

const leaderboardResponseSchemaResponseTransformer = (data: any) => {
    data.entries = data.entries.map((item: any) => leaderboardEntrySchemaResponseTransformer(item));
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3PublicLeaderboardResponseTransformer = async (data: any): Promise<GetV3PublicLeaderboardResponse> => {
    data = leaderboardResponseSchemaResponseTransformer(data);
    return data;
};

const userCodingHistoryResponseSchemaResponseTransformer = (data: any) => {
    data.periodStart = new Date(data.periodStart);
    data.periodEnd = new Date(data.periodEnd);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3PublicUsersByUserIdCodingHistoryResponseTransformer = async (data: any): Promise<GetV3PublicUsersByUserIdCodingHistoryResponse> => {
    data = userCodingHistoryResponseSchemaResponseTransformer(data);
    return data;
};

const userLanguageRankResponseSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3PublicUsersByUserIdLanguageRankResponseTransformer = async (data: any): Promise<GetV3PublicUsersByUserIdLanguageRankResponse> => {
    data = userLanguageRankResponseSchemaResponseTransformer(data);
    return data;
};

const userOverallRankResponseSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3PublicUsersByUserIdOverallRankResponseTransformer = async (data: any): Promise<GetV3PublicUsersByUserIdOverallRankResponse> => {
    data = userOverallRankResponseSchemaResponseTransformer(data);
    return data;
};

const userTopLanguagesRankResponseSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3PublicUsersByUserIdTopLanguagesRankResponseTransformer = async (data: any): Promise<GetV3PublicUsersByUserIdTopLanguagesRankResponse> => {
    data = userTopLanguagesRankResponseSchemaResponseTransformer(data);
    return data;
};

const tagResponseSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3TagsByTagIdResponseTransformer = async (data: any): Promise<GetV3TagsByTagIdResponse> => {
    data = tagResponseSchemaResponseTransformer(data);
    return data;
};

export const putV3TagsByTagIdResponseTransformer = async (data: any): Promise<PutV3TagsByTagIdResponse> => {
    data = tagResponseSchemaResponseTransformer(data);
    return data;
};

const tagHistoryResponseSchemaResponseTransformer = (data: any) => {
    data.tag = tagResponseSchemaResponseTransformer(data.tag);
    data.periodStart = new Date(data.periodStart);
    data.periodEnd = new Date(data.periodEnd);
    return data;
};

export const getV3TagsByTagIdHistoryResponseTransformer = async (data: any): Promise<GetV3TagsByTagIdHistoryResponse> => {
    data = tagHistoryResponseSchemaResponseTransformer(data);
    return data;
};

const workspaceEvaluationResponseSchemaResponseTransformer = (data: any) => {
    data.matchingTags = data.matchingTags.map((item: any) => tagResponseSchemaResponseTransformer(item));
    return data;
};

export const postV3TagsEvaluateResponseTransformer = async (data: any): Promise<PostV3TagsEvaluateResponse> => {
    data = workspaceEvaluationResponseSchemaResponseTransformer(data);
    return data;
};

export const getV3TagsResponseTransformer = async (data: any): Promise<GetV3TagsResponse> => {
    data = data.map((item: any) => tagResponseSchemaResponseTransformer(item));
    return data;
};

export const postV3TagsResponseTransformer = async (data: any): Promise<PostV3TagsResponse> => {
    data = tagResponseSchemaResponseTransformer(data);
    return data;
};

const tagTimeDataSchemaResponseTransformer = (data: any) => {
    data.tag = tagResponseSchemaResponseTransformer(data.tag);
    return data;
};

const tagTimeStatsResponseSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => tagTimeDataSchemaResponseTransformer(item));
    data.periodStart = new Date(data.periodStart);
    data.periodEnd = new Date(data.periodEnd);
    return data;
};

export const getV3TagsStatsResponseTransformer = async (data: any): Promise<GetV3TagsStatsResponse> => {
    data = tagTimeStatsResponseSchemaResponseTransformer(data);
    return data;
};

export const getV3TotalMinutesResponseTransformer = async (data: any): Promise<GetV3TotalMinutesResponse> => {
    data.cacheTimestamp = new Date(data.cacheTimestamp);
    return data;
};

export const getV3UsersByUserIdResponseTransformer = async (data: any): Promise<GetV3UsersByUserIdResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

const widgetUsageResponseSchemaResponseTransformer = (data: any) => {
    if (data.since) {
        data.since = new Date(data.since);
    }
    data.until = new Date(data.until);
    return data;
};

export const getV3UsersByUserIdPublicUsageResponseTransformer = async (data: any): Promise<GetV3UsersByUserIdPublicUsageResponse> => {
    data = widgetUsageResponseSchemaResponseTransformer(data);
    return data;
};

const userSelfPublicSchemaResponseTransformer = (data: any) => {
    if (data.planExpiresAt) {
        data.planExpiresAt = new Date(data.planExpiresAt);
    }
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getV3UsersSelfResponseTransformer = async (data: any): Promise<GetV3UsersSelfResponse> => {
    data = userSelfPublicSchemaResponseTransformer(data);
    return data;
};

export const postV3UsersSelfBioResponseTransformer = async (data: any): Promise<PostV3UsersSelfBioResponse> => {
    data = userSelfPublicSchemaResponseTransformer(data);
    return data;
};

export const postV3UsersSelfDeleteChallengeResponseTransformer = async (data: any): Promise<PostV3UsersSelfDeleteChallengeResponse> => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const getV3UsersSelfOverallRankResponseTransformer = async (data: any): Promise<GetV3UsersSelfOverallRankResponse> => {
    data = userOverallRankResponseSchemaResponseTransformer(data);
    return data;
};

export const getV3UsersSelfTopLanguagesRankResponseTransformer = async (data: any): Promise<GetV3UsersSelfTopLanguagesRankResponse> => {
    data = userTopLanguagesRankResponseSchemaResponseTransformer(data);
    return data;
};

export const postV3UsersSelfUsernameResponseTransformer = async (data: any): Promise<PostV3UsersSelfUsernameResponse> => {
    data = userSelfPublicSchemaResponseTransformer(data);
    return data;
};
