// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3002' | (string & {});
};

export type TokenRefreshResponse = {
    token: string;
    tokenV1: string;
};

export type DiscountPublic = {
    id: string;
    name: string;
    code: string;
    amount: number;
    /**
     * "percent" or "fixed"
     */
    amountType: string;
    expiresAt?: Date;
    /**
     * "once", "repeating", or "forever"
     */
    duration: string;
    durationInMonths?: number;
    /**
     * "published" or "draft"
     */
    status: string;
};

export type YearlyReportDataPublic = {
    topLanguages: Array<TopPublic>;
    hourlyDistribution: Array<TopPublic>;
    dailyDistribution: Array<TopPublic>;
};

export type CheckoutRequest = {
    type: 'monthly' | 'yearly';
    product: 'subscription' | 'onetime';
    locale?: string;
};

export type CheckoutResponse = {
    checkoutUrl: string;
    expiresAt: Date;
};

export type PricingPublic = {
    currency: string;
    /**
     * Price in cents
     */
    subscriptionMonthly: number;
    /**
     * Price in cents
     */
    subscriptionYearly: number;
    /**
     * Price in cents
     */
    onetimeMonthly: number;
    /**
     * Price in cents
     */
    onetimeYearly: number;
    /**
     * Yearly vs monthly×12 saving, in percent
     */
    annualDiscountPercent: number;
};

export type ProductPublic = {
    id: string;
    name: string;
    description: string;
    /**
     * Price in cents
     */
    price: number;
    currency: string;
    interval?: string;
};

export type WebhookResponse = {
    success: boolean;
    message: string;
};

export type LanguageRankingEntry = {
    user: UserPublic;
    totalMinutes: number;
    rank: number;
    percentile: number;
};

export type LanguageRankingResponse = {
    entries: Array<LanguageRankingEntry>;
    language: string;
    totalUsers: number;
    timeRangeDays?: number;
    updatedAt: Date;
};

export type LeaderboardEntry = {
    user: UserPublic;
    totalMinutes: number;
    rank: number;
};

export type LeaderboardResponse = {
    entries: Array<LeaderboardEntry>;
    totalUsers: number;
    updatedAt: Date;
};

export type UserCodingHistoryResponse = {
    userId: number;
    username: string;
    totalMinutes: number;
    data: Array<StatsTimeData>;
    periodStart: Date;
    periodEnd: Date;
    timeRangeDays: number;
    updatedAt: Date;
};

export type UserLanguageRankResponse = {
    userId: number;
    username: string;
    language: string;
    totalMinutes: number;
    rank: number;
    percentile: number;
    totalUsers: number;
    timeRangeDays?: number;
    updatedAt: Date;
};

export type StatsTimeData = {
    duration: number;
    time: string;
};

export type TagHistoryResponse = {
    tag: TagResponse;
    data: Array<StatsTimeData>;
    totalMinutes: number;
    periodStart: Date;
    periodEnd: Date;
};

export type WorkspaceEvaluationRequest = {
    workspaceName: string;
    language: string;
    gitOrigin?: string;
    gitBranch?: string;
    platform: string;
    editor: string;
    absoluteFile?: string;
    relativeFile: string;
};

export type WorkspaceEvaluationResponse = {
    matchingTags: Array<TagResponse>;
};

export type TagResponse = {
    id: string;
    name: string;
    color: string;
    emoji?: string;
    createdAt: Date;
    updatedAt: Date;
    rules?: {
        [key: string]: unknown;
    };
};

export type TagCreateRequest = {
    name: string;
    color: string;
    emoji?: string;
};

export type TagUpdateRequest = {
    name?: string;
    color?: string;
    emoji?: string;
    rules?: {
        [key: string]: unknown;
    };
};

export type TagTimeData = {
    tag: TagResponse;
    totalMinutes: number;
};

export type TagTimeStatsResponse = {
    data: Array<TagTimeData>;
    totalMinutes: number;
    periodStart: Date;
    periodEnd: Date;
};

export type UserPublic = {
    id: number;
    email?: string;
    username: string;
    avatar?: string;
    githubId?: number;
    githubLogin?: string;
    bio?: string;
    googleId?: string;
    plan: string;
    timezone?: string;
    createdAt: Date;
    updatedAt: Date;
};

export type WidgetStatusResponse = {
    username: string;
    plan: string;
    project?: string;
    language?: string;
    editor?: string;
    /**
     * Unix seconds.
     */
    lastActiveAt?: number;
    todayMinutes: number;
};

export type TopPublic = {
    field: string;
    minutes: number;
};

export type WidgetTopLanguagesResponse = {
    plan: string;
    days: number;
    limit: number;
    capped: boolean;
    items: Array<TopPublic>;
};

export type WidgetTopProjectsResponse = {
    plan: string;
    days: number;
    limit: number;
    capped: boolean;
    items: Array<TopPublic>;
};

export type WidgetUsageResponse = {
    plan: string;
    range: never;
    /**
     * Inclusive lower bound; null when `range=all`.
     */
    since?: Date;
    until: Date;
    tokens: number;
    inputTokens: number;
    cachedInputTokens: number;
    outputTokens: number;
    reasoningOutputTokens: number;
    estimatedCostUsd: number;
};

export type EventLogRequest = {
    eventTime: number;
    language: string;
    project: string;
    relativeFile: string;
    editor: string;
    platform: string;
    absoluteFile?: string;
    gitOrigin?: string;
    gitBranch?: string;
};

export type PyError = {
    status_code: number;
    detail: string;
};

export type UserSelfPublic = {
    id: number;
    email?: string;
    username: string;
    avatar?: string;
    githubId?: number;
    githubLogin?: string;
    bio?: string;
    googleId?: string;
    appleId?: string;
    plan: string;
    timezone?: string;
    uploadToken: string;
    planExpiresAt?: Date;
    planStatus?: string;
    createdAt: Date;
    updatedAt: Date;
};

export type UserDeleteResponse = {
    success: boolean;
    message: string;
};

export type EventLogPublic = {
    eventTime: number;
    language: string;
    project: string;
    relativeFile: string;
    editor: string;
    platform: string;
    absoluteFile: string;
    gitOrigin: string;
    gitBranch: string;
};

export type SimpleMinutes = {
    minutes: number;
};

export type UserOverallRankResponse = {
    userId: number;
    username: string;
    totalMinutes?: number;
    percentile?: number;
    timeRangeDays?: number;
    updatedAt: Date;
};

export type Facet = 'public' | 'private';

export type PrivacySettings = {
    v: number;
    profilePublic: boolean;
    widgetsEnabled: boolean;
    leaderboardListed: boolean;
    identity: {
        email: Facet;
        github: Facet;
    };
    status: {
        coding: Facet;
        project: Facet;
        language: Facet;
        editor: Facet;
    };
    history: {
        totalTime: Facet;
        languages: Facet;
        projects: Facet;
        calendar: Facet;
    };
};

export type StatsTimeResponse = {
    data: Array<StatsTimeData>;
};

export type StatsData = {
    duration: number;
    time: string;
    by: string;
};

export type StatsResponse = {
    data: Array<StatsData>;
};

export type TimeDistributionData = {
    hour: number;
    minute: number;
    count: number;
};

export type TimeDistributionResponse = {
    data: Array<TimeDistributionData>;
};

export type UserTopLanguageRankEntry = {
    language: string;
    totalMinutes: number;
    percentile?: number;
};

export type UserTopLanguagesRankResponse = {
    userId: number;
    username: string;
    entries: Array<UserTopLanguageRankEntry>;
    timeRangeDays?: number;
    updatedAt: Date;
};

export type WorkspaceFileActivity = {
    language: string;
    relativeFile: string;
    gitBranch: string;
    minutes: number;
};

export type WorkspaceSearchResult = {
    workspaceName: string;
};

export type WorkspaceSearchResponse = {
    results: Array<WorkspaceSearchResult>;
    totalResults: number;
};

export type ShieldResponse = {
    schemaVersion: number;
    logoSvg?: string;
    label: string;
    message: string;
    color: string;
    labelColor?: string;
};

export type PostV3AgentCliLinkApproveData = {
    body: {
        userCode: string;
    };
    path?: never;
    query?: never;
    url: '/v3/agent/cli/link/approve';
};

export type PostV3AgentCliLinkApproveErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PostV3AgentCliLinkApproveError = PostV3AgentCliLinkApproveErrors[keyof PostV3AgentCliLinkApproveErrors];

export type PostV3AgentCliLinkApproveResponses = {
    /**
     * Approved
     */
    200: {
        ok: boolean;
    };
};

export type PostV3AgentCliLinkApproveResponse = PostV3AgentCliLinkApproveResponses[keyof PostV3AgentCliLinkApproveResponses];

export type PostV3AgentCliLinkPollData = {
    body: {
        deviceCode: string;
    };
    path?: never;
    query?: never;
    url: '/v3/agent/cli/link/poll';
};

export type PostV3AgentCliLinkPollErrors = {
    /**
     * Invalid request
     */
    400: PyError;
};

export type PostV3AgentCliLinkPollError = PostV3AgentCliLinkPollErrors[keyof PostV3AgentCliLinkPollErrors];

export type PostV3AgentCliLinkPollResponses = {
    /**
     * Current status of the login
     */
    200: {
        status: 'pending' | 'approved' | 'expired';
        token?: string;
        userId?: number;
    };
};

export type PostV3AgentCliLinkPollResponse = PostV3AgentCliLinkPollResponses[keyof PostV3AgentCliLinkPollResponses];

export type PostV3AgentCliLinkStartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/agent/cli/link/start';
};

export type PostV3AgentCliLinkStartResponses = {
    /**
     * A pending link code pair
     */
    200: {
        deviceCode: string;
        userCode: string;
        verificationUri: string;
        verificationUriComplete: string;
        interval: number;
        expiresIn: number;
    };
};

export type PostV3AgentCliLinkStartResponse = PostV3AgentCliLinkStartResponses[keyof PostV3AgentCliLinkStartResponses];

export type GetV3AgentDashboardData = {
    body?: never;
    path?: never;
    query?: {
        range?: '24h' | '7d' | '30d' | 'all';
        /**
         * Restrict every aggregate to a single machine UUID.
         */
        machine_id?: string;
        /**
         * Restrict every aggregate to a single agent source (e.g. claude-code, codex, opencode, pi).
         */
        source?: string;
        /**
         * Custom window start (ISO 8601). Takes precedence over `days` and `range`; pair with `until` to scope aggregates to an exact span (e.g. start-of-today for a calendar-day view).
         */
        since?: Date;
        /**
         * Custom window end (ISO 8601). Defaults to the request time. Only meaningful alongside `since`.
         */
        until?: Date;
        /**
         * Rolling window of the last N days. Overrides `range`; ignored when `since` is given.
         */
        days?: number;
        /**
         * IANA timezone (e.g. Asia/Shanghai) used to align day/hour/week buckets to the user's local schedule. Defaults to UTC.
         */
        tz?: string;
    };
    url: '/v3/agent/dashboard';
};

export type GetV3AgentDashboardErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3AgentDashboardError = GetV3AgentDashboardErrors[keyof GetV3AgentDashboardErrors];

export type GetV3AgentDashboardResponses = {
    /**
     * Dashboard aggregates
     */
    200: {
        range: {
            key: string;
            since?: Date;
            until: Date;
        };
        bucket: 'hour' | 'day' | 'week';
        summary: {
            totalSessions: number;
            totalEvents: number;
            totalProjects: number;
            totalToolCalls: number;
            totalCommandCalls: number;
            totalInputTokens: number;
            totalCachedInputTokens: number;
            totalOutputTokens: number;
            totalReasoningOutputTokens: number;
            totalTokens: number;
            totalDurationMs: number;
            totalLinesAdded: number;
            totalLinesRemoved: number;
        };
        overviewBuckets: Array<{
            [key: string]: unknown;
        }>;
        tokenBuckets: Array<{
            [key: string]: unknown;
        }>;
        heatmap: Array<{
            [key: string]: unknown;
        }>;
        projectTokens: Array<{
            [key: string]: unknown;
        }>;
        modelCosts: Array<{
            [key: string]: unknown;
        }>;
        agentCosts: Array<{
            [key: string]: unknown;
        }>;
        tools: Array<{
            [key: string]: unknown;
        }>;
        availableSources: Array<string>;
    };
};

export type GetV3AgentDashboardResponse = GetV3AgentDashboardResponses[keyof GetV3AgentDashboardResponses];

export type PostV3AgentIngestData = {
    body: {
        rollups: Array<{
            [key: string]: unknown;
        }>;
        replace?: boolean;
    };
    headers: {
        /**
         * Stable per-host UUID. The CLI generates this on first run.
         */
        'X-Machine-Id': string;
    };
    path?: never;
    query?: never;
    url: '/v3/agent/ingest';
};

export type PostV3AgentIngestErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type PostV3AgentIngestError = PostV3AgentIngestErrors[keyof PostV3AgentIngestErrors];

export type PostV3AgentIngestResponses = {
    /**
     * Ingest result
     */
    200: {
        inserted: number;
        skipped: number;
        conflicts: number;
        conflictIds: Array<string>;
    };
};

export type PostV3AgentIngestResponse = PostV3AgentIngestResponses[keyof PostV3AgentIngestResponses];

export type GetV3AgentProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive substring filter.
         */
        q?: string;
        limit?: number;
    };
    url: '/v3/agent/projects';
};

export type GetV3AgentProjectsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3AgentProjectsError = GetV3AgentProjectsErrors[keyof GetV3AgentProjectsErrors];

export type GetV3AgentProjectsResponses = {
    /**
     * Project name page
     */
    200: {
        results: Array<{
            project: string;
            lastEventAt: Date;
        }>;
    };
};

export type GetV3AgentProjectsResponse = GetV3AgentProjectsResponses[keyof GetV3AgentProjectsResponses];

export type GetV3AgentSessionsByRollupKeyData = {
    body?: never;
    path: {
        rollup_key: string;
    };
    query?: never;
    url: '/v3/agent/sessions/{rollup_key}';
};

export type GetV3AgentSessionsByRollupKeyErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3AgentSessionsByRollupKeyError = GetV3AgentSessionsByRollupKeyErrors[keyof GetV3AgentSessionsByRollupKeyErrors];

export type GetV3AgentSessionsByRollupKeyResponses = {
    /**
     * Session detail
     */
    200: unknown;
};

export type GetV3AgentSessionsByRollupKeyTurnsData = {
    body?: never;
    path: {
        rollup_key: string;
    };
    query?: never;
    url: '/v3/agent/sessions/{rollup_key}/turns';
};

export type GetV3AgentSessionsByRollupKeyTurnsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3AgentSessionsByRollupKeyTurnsError = GetV3AgentSessionsByRollupKeyTurnsErrors[keyof GetV3AgentSessionsByRollupKeyTurnsErrors];

export type GetV3AgentSessionsByRollupKeyTurnsResponses = {
    /**
     * Turn list
     */
    200: unknown;
};

export type DeleteV3AgentSessionsData = {
    body?: never;
    headers: {
        'X-Machine-Id': string;
    };
    path?: never;
    query: {
        /**
         * Agent source id (e.g. claude, codex, opencode, pi).
         */
        source: string;
    };
    url: '/v3/agent/sessions';
};

export type DeleteV3AgentSessionsErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type DeleteV3AgentSessionsError = DeleteV3AgentSessionsErrors[keyof DeleteV3AgentSessionsErrors];

export type DeleteV3AgentSessionsResponses = {
    /**
     * Delete result
     */
    200: {
        deleted: number;
    };
};

export type DeleteV3AgentSessionsResponse = DeleteV3AgentSessionsResponses[keyof DeleteV3AgentSessionsResponses];

export type GetV3AgentSessionsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: string;
        source?: string;
        project_id?: string;
        machine_id?: string;
    };
    url: '/v3/agent/sessions';
};

export type GetV3AgentSessionsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3AgentSessionsError = GetV3AgentSessionsErrors[keyof GetV3AgentSessionsErrors];

export type GetV3AgentSessionsResponses = {
    /**
     * Session page
     */
    200: {
        sessions: Array<{
            rollupKey: string;
            sessionId: string;
            source: string;
            agent?: string;
            project?: string;
            projectId?: string;
            machineId: string;
            startedAt: Date;
            lastEventAt: Date;
            eventCount: number;
            turnCount: number;
            toolCallCount: number;
            inputTokens: number;
            outputTokens: number;
            totalTokens: number;
            linesAdded: number;
            linesRemoved: number;
            /**
             * Wall-clock session span in ms (first event to last event). This differs from the dashboard active-time metric, which sums per-turn active durations.
             */
            durationMs: number;
        }>;
        nextCursor: string;
    };
};

export type GetV3AgentSessionsResponse = GetV3AgentSessionsResponses[keyof GetV3AgentSessionsResponses];

export type PostV3AuthAppleData = {
    body: {
        identity_token: string;
        nonce: string;
        email?: string;
        full_name?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/apple';
};

export type PostV3AuthAppleErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Apple identity token verification failed
     */
    401: unknown;
};

export type PostV3AuthAppleResponses = {
    /**
     * Signed in; auth cookies set
     */
    200: {
        success: boolean;
        user_id: number;
    };
};

export type PostV3AuthAppleResponse = PostV3AuthAppleResponses[keyof PostV3AuthAppleResponses];

export type DeleteV3AuthAppleLinkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/apple/link';
};

export type DeleteV3AuthAppleLinkErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type DeleteV3AuthAppleLinkError = DeleteV3AuthAppleLinkErrors[keyof DeleteV3AuthAppleLinkErrors];

export type DeleteV3AuthAppleLinkResponses = {
    /**
     * Disconnected (or wasn't linked).
     */
    200: {
        success: boolean;
        outcome: 'unlinked' | 'not-linked';
    };
};

export type DeleteV3AuthAppleLinkResponse = DeleteV3AuthAppleLinkResponses[keyof DeleteV3AuthAppleLinkResponses];

export type PostV3AuthAppleLinkData = {
    body: {
        identity_token: string;
        /**
         * Raw nonce passed to AppleID.auth.init.
         */
        nonce: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/apple/link';
};

export type PostV3AuthAppleLinkErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Request conflicts with current state
     */
    409: PyError;
};

export type PostV3AuthAppleLinkError = PostV3AuthAppleLinkErrors[keyof PostV3AuthAppleLinkErrors];

export type PostV3AuthAppleLinkResponses = {
    /**
     * Linked (or already linked to the same Apple identity).
     */
    200: {
        success: boolean;
        outcome: 'linked' | 'already-yours';
    };
};

export type PostV3AuthAppleLinkResponse = PostV3AuthAppleLinkResponses[keyof PostV3AuthAppleLinkResponses];

export type PostV3AuthAppleNativeData = {
    body: {
        identity_token: string;
        authorization_code?: string;
        nonce: string;
        email?: string;
        full_name?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/apple/native';
};

export type PostV3AuthAppleNativeErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Apple identity token verification failed
     */
    401: unknown;
};

export type PostV3AuthAppleNativeResponses = {
    /**
     * Session token issued
     */
    200: {
        token: string;
        user_id: number;
    };
};

export type PostV3AuthAppleNativeResponse = PostV3AuthAppleNativeResponses[keyof PostV3AuthAppleNativeResponses];

export type GetV3AuthGithubData = {
    body?: never;
    path?: never;
    query: {
        code: string;
    };
    url: '/v3/auth/github';
};

export type DeleteV3AuthGithubLinkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/github/link';
};

export type DeleteV3AuthGithubLinkErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type DeleteV3AuthGithubLinkError = DeleteV3AuthGithubLinkErrors[keyof DeleteV3AuthGithubLinkErrors];

export type DeleteV3AuthGithubLinkResponses = {
    /**
     * Disconnected (or wasn't linked).
     */
    200: {
        success: boolean;
        outcome: 'unlinked' | 'not-linked';
    };
};

export type DeleteV3AuthGithubLinkResponse = DeleteV3AuthGithubLinkResponses[keyof DeleteV3AuthGithubLinkResponses];

export type GetV3AuthGithubNativeCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
        state?: string;
    };
    url: '/v3/auth/github/native-callback';
};

export type GetV3AuthGithubStartData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * When `1`, the callback will link the GitHub identity to the currently signed-in user instead of provisioning a new account.
         */
        link?: '1';
    };
    url: '/v3/auth/github/start';
};

export type PostV3AuthGoogleData = {
    body: {
        credential: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/google';
};

export type DeleteV3AuthGoogleLinkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/google/link';
};

export type DeleteV3AuthGoogleLinkErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type DeleteV3AuthGoogleLinkError = DeleteV3AuthGoogleLinkErrors[keyof DeleteV3AuthGoogleLinkErrors];

export type DeleteV3AuthGoogleLinkResponses = {
    /**
     * Disconnected (or wasn't linked).
     */
    200: {
        success: boolean;
        outcome: 'unlinked' | 'not-linked';
    };
};

export type DeleteV3AuthGoogleLinkResponse = DeleteV3AuthGoogleLinkResponses[keyof DeleteV3AuthGoogleLinkResponses];

export type PostV3AuthGoogleLinkData = {
    body: {
        /**
         * Google ID token (same JWT as /v3/auth/google).
         */
        credential: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/google/link';
};

export type PostV3AuthGoogleLinkErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Request conflicts with current state
     */
    409: PyError;
};

export type PostV3AuthGoogleLinkError = PostV3AuthGoogleLinkErrors[keyof PostV3AuthGoogleLinkErrors];

export type PostV3AuthGoogleLinkResponses = {
    /**
     * Linked (or already linked to the same Google identity).
     */
    200: {
        success: boolean;
        outcome: 'linked' | 'already-yours';
    };
};

export type PostV3AuthGoogleLinkResponse = PostV3AuthGoogleLinkResponses[keyof PostV3AuthGoogleLinkResponses];

export type PostV3AuthGoogleNativeData = {
    body: {
        code: string;
        code_verifier: string;
        redirect_uri: string;
        client_id?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/google/native';
};

export type PostV3AuthGoogleNativeErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Google token verification failed
     */
    401: unknown;
};

export type PostV3AuthGoogleNativeResponses = {
    /**
     * Session token issued
     */
    200: {
        token: string;
        user_id: number;
    };
};

export type PostV3AuthGoogleNativeResponse = PostV3AuthGoogleNativeResponses[keyof PostV3AuthGoogleNativeResponses];

export type PostV3AuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/login';
};

export type PostV3AuthLoginErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Endpoint not configured
     */
    404: unknown;
    /**
     * Too many attempts
     */
    429: unknown;
};

export type PostV3AuthLoginError = PostV3AuthLoginErrors[keyof PostV3AuthLoginErrors];

export type PostV3AuthLoginResponses = {
    /**
     * Session token issued
     */
    200: {
        token: string;
        user_id: number;
    };
};

export type PostV3AuthLoginResponse = PostV3AuthLoginResponses[keyof PostV3AuthLoginResponses];

export type PostV3AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/logout';
};

export type PostV3AuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        message: string;
    };
};

export type PostV3AuthLogoutResponse = PostV3AuthLogoutResponses[keyof PostV3AuthLogoutResponses];

export type PostV3AuthRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/refresh-token';
};

export type PostV3AuthRefreshTokenErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PostV3AuthRefreshTokenError = PostV3AuthRefreshTokenErrors[keyof PostV3AuthRefreshTokenErrors];

export type PostV3AuthRefreshTokenResponses = {
    /**
     * New tokens
     */
    200: TokenRefreshResponse;
};

export type PostV3AuthRefreshTokenResponse = PostV3AuthRefreshTokenResponses[keyof PostV3AuthRefreshTokenResponses];

export type PostV3DevBeData = {
    body?: never;
    path?: never;
    query: {
        uid: number;
    };
    url: '/v3/dev/be';
};

export type PostV3DevBeErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PostV3DevBeError = PostV3DevBeErrors[keyof PostV3DevBeErrors];

export type PostV3DevBeResponses = {
    /**
     * Cookies set; no body.
     */
    201: unknown;
};

export type GetV3DiscountsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/discounts/active';
};

export type GetV3DiscountsActiveErrors = {
    /**
     * Invalid request
     */
    500: PyError;
};

export type GetV3DiscountsActiveError = GetV3DiscountsActiveErrors[keyof GetV3DiscountsActiveErrors];

export type GetV3DiscountsActiveResponses = {
    /**
     * Active discounts
     */
    200: Array<DiscountPublic>;
};

export type GetV3DiscountsActiveResponse = GetV3DiscountsActiveResponses[keyof GetV3DiscountsActiveResponses];

export type GetV3IcalendarFeedIcsData = {
    body?: never;
    path?: never;
    query?: {
        target?: 'language' | 'workspace' | 'editor' | 'platform';
        start_date?: Date;
        end_date?: Date;
        minimum_duration_minutes?: number;
        timezone?: string;
    };
    url: '/v3/icalendar/feed.ics';
};

export type GetV3IcalendarFeedIcsErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3IcalendarFeedIcsError = GetV3IcalendarFeedIcsErrors[keyof GetV3IcalendarFeedIcsErrors];

export type GetV3IcalendarFeedIcsResponses = {
    /**
     * iCalendar feed
     */
    200: string;
};

export type GetV3IcalendarFeedIcsResponse = GetV3IcalendarFeedIcsResponses[keyof GetV3IcalendarFeedIcsResponses];

export type GetV3IcalendarInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/icalendar/info';
};

export type GetV3IcalendarInfoErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3IcalendarInfoError = GetV3IcalendarInfoErrors[keyof GetV3IcalendarInfoErrors];

export type GetV3IcalendarInfoResponses = {
    /**
     * Feed options + docs
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetV3IcalendarInfoResponse = GetV3IcalendarInfoResponses[keyof GetV3IcalendarInfoResponses];

export type GetV3LogsYearlyReportDataData = {
    body?: never;
    path?: never;
    query: {
        user_id: number;
        year?: number;
        timezone?: string;
    };
    url: '/v3/logs/yearly-report-data';
};

export type GetV3LogsYearlyReportDataErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3LogsYearlyReportDataError = GetV3LogsYearlyReportDataErrors[keyof GetV3LogsYearlyReportDataErrors];

export type GetV3LogsYearlyReportDataResponses = {
    /**
     * Yearly report
     */
    200: YearlyReportDataPublic;
};

export type GetV3LogsYearlyReportDataResponse = GetV3LogsYearlyReportDataResponses[keyof GetV3LogsYearlyReportDataResponses];

export type DeleteV3MachinesByMachineIdData = {
    body?: never;
    path: {
        machine_id: string;
    };
    query?: never;
    url: '/v3/machines/{machine_id}';
};

export type DeleteV3MachinesByMachineIdErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type DeleteV3MachinesByMachineIdError = DeleteV3MachinesByMachineIdErrors[keyof DeleteV3MachinesByMachineIdErrors];

export type DeleteV3MachinesByMachineIdResponses = {
    /**
     * Delete result
     */
    200: {
        deletedMachine: boolean;
        deletedSessions: number;
    };
};

export type DeleteV3MachinesByMachineIdResponse = DeleteV3MachinesByMachineIdResponses[keyof DeleteV3MachinesByMachineIdResponses];

export type PatchV3MachinesByMachineIdData = {
    body: {
        displayName: string;
    };
    path: {
        machine_id: string;
    };
    query?: never;
    url: '/v3/machines/{machine_id}';
};

export type PatchV3MachinesByMachineIdErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PatchV3MachinesByMachineIdError = PatchV3MachinesByMachineIdErrors[keyof PatchV3MachinesByMachineIdErrors];

export type PatchV3MachinesByMachineIdResponses = {
    /**
     * Updated machine
     */
    200: {
        [key: string]: unknown;
    };
};

export type PatchV3MachinesByMachineIdResponse = PatchV3MachinesByMachineIdResponses[keyof PatchV3MachinesByMachineIdResponses];

export type GetV3MachinesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/machines';
};

export type GetV3MachinesErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3MachinesError = GetV3MachinesErrors[keyof GetV3MachinesErrors];

export type GetV3MachinesResponses = {
    /**
     * Machine list
     */
    200: {
        machines?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type GetV3MachinesResponse = GetV3MachinesResponses[keyof GetV3MachinesResponses];

export type GetV3MetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/metrics';
};

export type GetV3MetricsResponses = {
    /**
     * Prometheus text exposition format
     */
    200: string;
};

export type GetV3MetricsResponse = GetV3MetricsResponses[keyof GetV3MetricsResponses];

export type PostV3PaymentsCheckoutData = {
    body: CheckoutRequest;
    path?: never;
    query?: never;
    url: '/v3/payments/checkout';
};

export type PostV3PaymentsCheckoutErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
    /**
     * Invalid request
     */
    500: PyError;
};

export type PostV3PaymentsCheckoutError = PostV3PaymentsCheckoutErrors[keyof PostV3PaymentsCheckoutErrors];

export type PostV3PaymentsCheckoutResponses = {
    /**
     * Checkout URL
     */
    200: CheckoutResponse;
};

export type PostV3PaymentsCheckoutResponse = PostV3PaymentsCheckoutResponses[keyof PostV3PaymentsCheckoutResponses];

export type GetV3PaymentsPricingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/payments/pricing';
};

export type GetV3PaymentsPricingResponses = {
    /**
     * Pricing
     */
    200: PricingPublic;
};

export type GetV3PaymentsPricingResponse = GetV3PaymentsPricingResponses[keyof GetV3PaymentsPricingResponses];

export type GetV3PaymentsProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/payments/products';
};

export type GetV3PaymentsProductsResponses = {
    /**
     * Products
     */
    200: Array<ProductPublic>;
};

export type GetV3PaymentsProductsResponse = GetV3PaymentsProductsResponses[keyof GetV3PaymentsProductsResponses];

export type PostV3PaymentsWebhooksLemonsqueezyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/payments/webhooks/lemonsqueezy';
};

export type PostV3PaymentsWebhooksLemonsqueezyErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type PostV3PaymentsWebhooksLemonsqueezyError = PostV3PaymentsWebhooksLemonsqueezyErrors[keyof PostV3PaymentsWebhooksLemonsqueezyErrors];

export type PostV3PaymentsWebhooksLemonsqueezyResponses = {
    /**
     * Webhook processed
     */
    200: WebhookResponse;
};

export type PostV3PaymentsWebhooksLemonsqueezyResponse = PostV3PaymentsWebhooksLemonsqueezyResponses[keyof PostV3PaymentsWebhooksLemonsqueezyResponses];

export type GetV3PublicLanguageRankingData = {
    body?: never;
    path?: never;
    query: {
        language: string;
        limit?: number;
        days?: number;
    };
    url: '/v3/public/language-ranking';
};

export type GetV3PublicLanguageRankingErrors = {
    /**
     * Invalid request
     */
    400: PyError;
};

export type GetV3PublicLanguageRankingError = GetV3PublicLanguageRankingErrors[keyof GetV3PublicLanguageRankingErrors];

export type GetV3PublicLanguageRankingResponses = {
    /**
     * Language ranking
     */
    200: LanguageRankingResponse;
};

export type GetV3PublicLanguageRankingResponse = GetV3PublicLanguageRankingResponses[keyof GetV3PublicLanguageRankingResponses];

export type GetV3PublicLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        days?: number;
    };
    url: '/v3/public/leaderboard';
};

export type GetV3PublicLeaderboardResponses = {
    /**
     * Leaderboard
     */
    200: LeaderboardResponse;
};

export type GetV3PublicLeaderboardResponse = GetV3PublicLeaderboardResponses[keyof GetV3PublicLeaderboardResponses];

export type GetV3PublicUsersByUserIdCodingHistoryData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        days?: number;
    };
    url: '/v3/public/users/{user_id}/coding-history';
};

export type GetV3PublicUsersByUserIdCodingHistoryErrors = {
    /**
     * Insufficient permissions
     */
    403: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3PublicUsersByUserIdCodingHistoryError = GetV3PublicUsersByUserIdCodingHistoryErrors[keyof GetV3PublicUsersByUserIdCodingHistoryErrors];

export type GetV3PublicUsersByUserIdCodingHistoryResponses = {
    /**
     * Coding history
     */
    200: UserCodingHistoryResponse;
};

export type GetV3PublicUsersByUserIdCodingHistoryResponse = GetV3PublicUsersByUserIdCodingHistoryResponses[keyof GetV3PublicUsersByUserIdCodingHistoryResponses];

export type GetV3PublicUsersByUserIdLanguageRankData = {
    body?: never;
    path: {
        user_id: number;
    };
    query: {
        language: string;
        days?: number;
    };
    url: '/v3/public/users/{user_id}/language-rank';
};

export type GetV3PublicUsersByUserIdLanguageRankErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3PublicUsersByUserIdLanguageRankError = GetV3PublicUsersByUserIdLanguageRankErrors[keyof GetV3PublicUsersByUserIdLanguageRankErrors];

export type GetV3PublicUsersByUserIdLanguageRankResponses = {
    /**
     * User language rank
     */
    200: UserLanguageRankResponse;
};

export type GetV3PublicUsersByUserIdLanguageRankResponse = GetV3PublicUsersByUserIdLanguageRankResponses[keyof GetV3PublicUsersByUserIdLanguageRankResponses];

export type GetV3PublicUsersByUserIdOverallRankData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        days?: number;
    };
    url: '/v3/public/users/{user_id}/overall-rank';
};

export type GetV3PublicUsersByUserIdOverallRankErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3PublicUsersByUserIdOverallRankError = GetV3PublicUsersByUserIdOverallRankErrors[keyof GetV3PublicUsersByUserIdOverallRankErrors];

export type GetV3PublicUsersByUserIdOverallRankResponses = {
    /**
     * Overall rank
     */
    200: UserOverallRankResponse;
};

export type GetV3PublicUsersByUserIdOverallRankResponse = GetV3PublicUsersByUserIdOverallRankResponses[keyof GetV3PublicUsersByUserIdOverallRankResponses];

export type GetV3PublicUsersByUserIdTopLanguagesRankData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        top_n?: number;
        days?: number;
    };
    url: '/v3/public/users/{user_id}/top-languages-rank';
};

export type GetV3PublicUsersByUserIdTopLanguagesRankErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3PublicUsersByUserIdTopLanguagesRankError = GetV3PublicUsersByUserIdTopLanguagesRankErrors[keyof GetV3PublicUsersByUserIdTopLanguagesRankErrors];

export type GetV3PublicUsersByUserIdTopLanguagesRankResponses = {
    /**
     * Top-language rankings
     */
    200: UserTopLanguagesRankResponse;
};

export type GetV3PublicUsersByUserIdTopLanguagesRankResponse = GetV3PublicUsersByUserIdTopLanguagesRankResponses[keyof GetV3PublicUsersByUserIdTopLanguagesRankResponses];

export type DeleteV3TagsByTagIdData = {
    body?: never;
    path: {
        tag_id: string;
    };
    query?: never;
    url: '/v3/tags/{tag_id}';
};

export type DeleteV3TagsByTagIdErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type DeleteV3TagsByTagIdError = DeleteV3TagsByTagIdErrors[keyof DeleteV3TagsByTagIdErrors];

export type DeleteV3TagsByTagIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteV3TagsByTagIdResponse = DeleteV3TagsByTagIdResponses[keyof DeleteV3TagsByTagIdResponses];

export type GetV3TagsByTagIdData = {
    body?: never;
    path: {
        tag_id: string;
    };
    query?: never;
    url: '/v3/tags/{tag_id}';
};

export type GetV3TagsByTagIdErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3TagsByTagIdError = GetV3TagsByTagIdErrors[keyof GetV3TagsByTagIdErrors];

export type GetV3TagsByTagIdResponses = {
    /**
     * Tag
     */
    200: TagResponse;
};

export type GetV3TagsByTagIdResponse = GetV3TagsByTagIdResponses[keyof GetV3TagsByTagIdResponses];

export type PutV3TagsByTagIdData = {
    body: TagUpdateRequest;
    path: {
        tag_id: string;
    };
    query?: never;
    url: '/v3/tags/{tag_id}';
};

export type PutV3TagsByTagIdErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PutV3TagsByTagIdError = PutV3TagsByTagIdErrors[keyof PutV3TagsByTagIdErrors];

export type PutV3TagsByTagIdResponses = {
    /**
     * Updated tag
     */
    200: TagResponse;
};

export type PutV3TagsByTagIdResponse = PutV3TagsByTagIdResponses[keyof PutV3TagsByTagIdResponses];

export type GetV3TagsByTagIdHistoryData = {
    body?: never;
    path: {
        tag_id: string;
    };
    query?: {
        start_datetime?: Date;
        end_datetime?: Date;
        group_by?: 'day' | 'week' | 'month';
    };
    url: '/v3/tags/{tag_id}/history';
};

export type GetV3TagsByTagIdHistoryErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3TagsByTagIdHistoryError = GetV3TagsByTagIdHistoryErrors[keyof GetV3TagsByTagIdHistoryErrors];

export type GetV3TagsByTagIdHistoryResponses = {
    /**
     * Tag history
     */
    200: TagHistoryResponse;
};

export type GetV3TagsByTagIdHistoryResponse = GetV3TagsByTagIdHistoryResponses[keyof GetV3TagsByTagIdHistoryResponses];

export type PostV3TagsEvaluateData = {
    body: WorkspaceEvaluationRequest;
    path?: never;
    query?: never;
    url: '/v3/tags/evaluate';
};

export type PostV3TagsEvaluateErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type PostV3TagsEvaluateError = PostV3TagsEvaluateErrors[keyof PostV3TagsEvaluateErrors];

export type PostV3TagsEvaluateResponses = {
    /**
     * Matching tags
     */
    200: WorkspaceEvaluationResponse;
};

export type PostV3TagsEvaluateResponse = PostV3TagsEvaluateResponses[keyof PostV3TagsEvaluateResponses];

export type GetV3TagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/tags';
};

export type GetV3TagsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3TagsError = GetV3TagsErrors[keyof GetV3TagsErrors];

export type GetV3TagsResponses = {
    /**
     * Tag list
     */
    200: Array<TagResponse>;
};

export type GetV3TagsResponse = GetV3TagsResponses[keyof GetV3TagsResponses];

export type PostV3TagsData = {
    body: TagCreateRequest;
    path?: never;
    query?: never;
    url: '/v3/tags';
};

export type PostV3TagsErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PostV3TagsError = PostV3TagsErrors[keyof PostV3TagsErrors];

export type PostV3TagsResponses = {
    /**
     * Created
     */
    201: TagResponse;
};

export type PostV3TagsResponse = PostV3TagsResponses[keyof PostV3TagsResponses];

export type GetV3TagsStatsData = {
    body?: never;
    path?: never;
    query?: {
        start_datetime?: Date;
        end_datetime?: Date;
        /**
         * Comma-separated tag UUIDs
         */
        tag_ids?: string;
    };
    url: '/v3/tags/stats';
};

export type GetV3TagsStatsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3TagsStatsError = GetV3TagsStatsErrors[keyof GetV3TagsStatsErrors];

export type GetV3TagsStatsResponses = {
    /**
     * Tag time stats
     */
    200: TagTimeStatsResponse;
};

export type GetV3TagsStatsResponse = GetV3TagsStatsResponses[keyof GetV3TagsStatsResponses];

export type GetV3TotalMinutesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/total-minutes';
};

export type GetV3TotalMinutesResponses = {
    /**
     * Total minutes payload
     */
    200: {
        totalMinutes: number;
        last24HMinutes: number;
        cacheTimestamp: Date;
    };
};

export type GetV3TotalMinutesResponse = GetV3TotalMinutesResponses[keyof GetV3TotalMinutesResponses];

export type GetV3UsersByUserIdData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/v3/users/{user_id}';
};

export type GetV3UsersByUserIdErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3UsersByUserIdError = GetV3UsersByUserIdErrors[keyof GetV3UsersByUserIdErrors];

export type GetV3UsersByUserIdResponses = {
    /**
     * User profile
     */
    200: UserPublic;
};

export type GetV3UsersByUserIdResponse = GetV3UsersByUserIdResponses[keyof GetV3UsersByUserIdResponses];

export type GetV3UsersByUserIdPublicStatusData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        /**
         * CSV of fields to expose; only project/language/editor honored.
         */
        show?: string;
    };
    url: '/v3/users/{user_id}/public/status';
};

export type GetV3UsersByUserIdPublicStatusErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3UsersByUserIdPublicStatusError = GetV3UsersByUserIdPublicStatusErrors[keyof GetV3UsersByUserIdPublicStatusErrors];

export type GetV3UsersByUserIdPublicStatusResponses = {
    /**
     * Widget status payload
     */
    200: WidgetStatusResponse;
};

export type GetV3UsersByUserIdPublicStatusResponse = GetV3UsersByUserIdPublicStatusResponses[keyof GetV3UsersByUserIdPublicStatusResponses];

export type GetV3UsersByUserIdPublicTopLanguagesData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        days?: number;
        limit?: number;
    };
    url: '/v3/users/{user_id}/public/top-languages';
};

export type GetV3UsersByUserIdPublicTopLanguagesErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3UsersByUserIdPublicTopLanguagesError = GetV3UsersByUserIdPublicTopLanguagesErrors[keyof GetV3UsersByUserIdPublicTopLanguagesErrors];

export type GetV3UsersByUserIdPublicTopLanguagesResponses = {
    /**
     * Top languages by minutes
     */
    200: WidgetTopLanguagesResponse;
};

export type GetV3UsersByUserIdPublicTopLanguagesResponse = GetV3UsersByUserIdPublicTopLanguagesResponses[keyof GetV3UsersByUserIdPublicTopLanguagesResponses];

export type GetV3UsersByUserIdPublicTopProjectsData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        days?: number;
        limit?: number;
    };
    url: '/v3/users/{user_id}/public/top-projects';
};

export type GetV3UsersByUserIdPublicTopProjectsErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3UsersByUserIdPublicTopProjectsError = GetV3UsersByUserIdPublicTopProjectsErrors[keyof GetV3UsersByUserIdPublicTopProjectsErrors];

export type GetV3UsersByUserIdPublicTopProjectsResponses = {
    /**
     * Top projects by minutes
     */
    200: WidgetTopProjectsResponse;
};

export type GetV3UsersByUserIdPublicTopProjectsResponse = GetV3UsersByUserIdPublicTopProjectsResponses[keyof GetV3UsersByUserIdPublicTopProjectsResponses];

export type GetV3UsersByUserIdPublicUsageData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        /**
         * Window: calendar-aligned `today`/`week`/`month`/`year` (anchored to the user's timezone), rolling `24h`/`7d`/`30d`/`365d` (now − N days), or `all` for full history. Free plan is capped to the last 30 days regardless.
         */
        range?: never;
    };
    url: '/v3/users/{user_id}/public/usage';
};

export type GetV3UsersByUserIdPublicUsageErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3UsersByUserIdPublicUsageError = GetV3UsersByUserIdPublicUsageErrors[keyof GetV3UsersByUserIdPublicUsageErrors];

export type GetV3UsersByUserIdPublicUsageResponses = {
    /**
     * Usage snapshot payload
     */
    200: WidgetUsageResponse;
};

export type GetV3UsersByUserIdPublicUsageResponse = GetV3UsersByUserIdPublicUsageResponses[keyof GetV3UsersByUserIdPublicUsageResponses];

export type PostV3UsersEventLogData = {
    body: EventLogRequest;
    path?: never;
    query?: never;
    url: '/v3/users/event-log';
};

export type PostV3UsersEventLogErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type PostV3UsersEventLogError = PostV3UsersEventLogErrors[keyof PostV3UsersEventLogErrors];

export type PostV3UsersEventLogResponses = {
    /**
     * Logged
     */
    201: unknown;
};

export type DeleteV3UsersSelfData = {
    body: {
        /**
         * Token issued by POST /v3/users/self/delete-challenge
         */
        challenge: string;
        /**
         * Must match the caller's current username
         */
        confirmUsername: string;
    };
    path?: never;
    query?: never;
    url: '/v3/users/self';
};

export type DeleteV3UsersSelfErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type DeleteV3UsersSelfError = DeleteV3UsersSelfErrors[keyof DeleteV3UsersSelfErrors];

export type DeleteV3UsersSelfResponses = {
    /**
     * Delete result
     */
    200: UserDeleteResponse;
};

export type DeleteV3UsersSelfResponse = DeleteV3UsersSelfResponses[keyof DeleteV3UsersSelfResponses];

export type GetV3UsersSelfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self';
};

export type GetV3UsersSelfErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfError = GetV3UsersSelfErrors[keyof GetV3UsersSelfErrors];

export type GetV3UsersSelfResponses = {
    /**
     * Current user
     */
    200: UserSelfPublic;
};

export type GetV3UsersSelfResponse = GetV3UsersSelfResponses[keyof GetV3UsersSelfResponses];

export type PostV3UsersSelfBioData = {
    body: {
        bio?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/users/self/bio';
};

export type PostV3UsersSelfBioErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PostV3UsersSelfBioError = PostV3UsersSelfBioErrors[keyof PostV3UsersSelfBioErrors];

export type PostV3UsersSelfBioResponses = {
    /**
     * Updated user
     */
    200: UserSelfPublic;
};

export type PostV3UsersSelfBioResponse = PostV3UsersSelfBioResponses[keyof PostV3UsersSelfBioResponses];

export type DeleteV3UsersSelfDataData = {
    body: {
        /**
         * Token issued by POST /v3/users/self/delete-challenge?purpose=data
         */
        challenge: string;
        /**
         * Must match the caller's current username
         */
        confirmUsername: string;
    };
    path?: never;
    query?: never;
    url: '/v3/users/self/data';
};

export type DeleteV3UsersSelfDataErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type DeleteV3UsersSelfDataError = DeleteV3UsersSelfDataErrors[keyof DeleteV3UsersSelfDataErrors];

export type DeleteV3UsersSelfDataResponses = {
    /**
     * Delete result
     */
    200: UserDeleteResponse;
};

export type DeleteV3UsersSelfDataResponse = DeleteV3UsersSelfDataResponses[keyof DeleteV3UsersSelfDataResponses];

export type PostV3UsersSelfDeleteChallengeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Which DELETE route the token authorises.
         */
        purpose: 'account' | 'data';
    };
    url: '/v3/users/self/delete-challenge';
};

export type PostV3UsersSelfDeleteChallengeErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type PostV3UsersSelfDeleteChallengeError = PostV3UsersSelfDeleteChallengeErrors[keyof PostV3UsersSelfDeleteChallengeErrors];

export type PostV3UsersSelfDeleteChallengeResponses = {
    /**
     * Challenge token issued
     */
    201: {
        challenge: string;
        expiresAt: Date;
        purpose: 'account' | 'data';
    };
};

export type PostV3UsersSelfDeleteChallengeResponse = PostV3UsersSelfDeleteChallengeResponses[keyof PostV3UsersSelfDeleteChallengeResponses];

export type GetV3UsersSelfExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self/export';
};

export type GetV3UsersSelfExportErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfExportError = GetV3UsersSelfExportErrors[keyof GetV3UsersSelfExportErrors];

export type GetV3UsersSelfExportResponses = {
    /**
     * CSV stream
     */
    200: Blob | File;
};

export type GetV3UsersSelfExportResponse = GetV3UsersSelfExportResponses[keyof GetV3UsersSelfExportResponses];

export type GetV3UsersSelfLanguagesRecentData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        days?: number;
    };
    url: '/v3/users/self/languages/recent';
};

export type GetV3UsersSelfLanguagesRecentErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfLanguagesRecentError = GetV3UsersSelfLanguagesRecentErrors[keyof GetV3UsersSelfLanguagesRecentErrors];

export type GetV3UsersSelfLanguagesRecentResponses = {
    /**
     * Language names ordered by recency
     */
    200: Array<string>;
};

export type GetV3UsersSelfLanguagesRecentResponse = GetV3UsersSelfLanguagesRecentResponses[keyof GetV3UsersSelfLanguagesRecentResponses];

export type GetV3UsersSelfLatestLogsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/v3/users/self/latest-logs';
};

export type GetV3UsersSelfLatestLogsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfLatestLogsError = GetV3UsersSelfLatestLogsErrors[keyof GetV3UsersSelfLatestLogsErrors];

export type GetV3UsersSelfLatestLogsResponses = {
    /**
     * Event logs newest first
     */
    200: Array<EventLogPublic>;
};

export type GetV3UsersSelfLatestLogsResponse = GetV3UsersSelfLatestLogsResponses[keyof GetV3UsersSelfLatestLogsResponses];

export type GetV3UsersSelfMinutesData = {
    body?: never;
    path?: never;
    query?: {
        minutes?: number;
        start_time?: Date;
        end_time?: Date;
    };
    url: '/v3/users/self/minutes';
};

export type GetV3UsersSelfMinutesErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfMinutesError = GetV3UsersSelfMinutesErrors[keyof GetV3UsersSelfMinutesErrors];

export type GetV3UsersSelfMinutesResponses = {
    /**
     * Minutes count
     */
    200: SimpleMinutes;
};

export type GetV3UsersSelfMinutesResponse = GetV3UsersSelfMinutesResponses[keyof GetV3UsersSelfMinutesResponses];

export type GetV3UsersSelfOverallRankData = {
    body?: never;
    path?: never;
    query?: {
        start_time?: Date;
        end_time?: Date;
        days?: number;
    };
    url: '/v3/users/self/overall-rank';
};

export type GetV3UsersSelfOverallRankErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3UsersSelfOverallRankError = GetV3UsersSelfOverallRankErrors[keyof GetV3UsersSelfOverallRankErrors];

export type GetV3UsersSelfOverallRankResponses = {
    /**
     * Overall rank
     */
    200: UserOverallRankResponse;
};

export type GetV3UsersSelfOverallRankResponse = GetV3UsersSelfOverallRankResponses[keyof GetV3UsersSelfOverallRankResponses];

export type GetV3UsersSelfPrivacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self/privacy';
};

export type GetV3UsersSelfPrivacyErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfPrivacyError = GetV3UsersSelfPrivacyErrors[keyof GetV3UsersSelfPrivacyErrors];

export type GetV3UsersSelfPrivacyResponses = {
    /**
     * Privacy settings
     */
    200: PrivacySettings;
};

export type GetV3UsersSelfPrivacyResponse = GetV3UsersSelfPrivacyResponses[keyof GetV3UsersSelfPrivacyResponses];

export type PostV3UsersSelfPrivacyData = {
    body: PrivacySettings;
    path?: never;
    query?: never;
    url: '/v3/users/self/privacy';
};

export type PostV3UsersSelfPrivacyErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type PostV3UsersSelfPrivacyError = PostV3UsersSelfPrivacyErrors[keyof PostV3UsersSelfPrivacyErrors];

export type PostV3UsersSelfPrivacyResponses = {
    /**
     * Updated privacy settings
     */
    200: PrivacySettings;
};

export type PostV3UsersSelfPrivacyResponse = PostV3UsersSelfPrivacyResponses[keyof PostV3UsersSelfPrivacyResponses];

export type GetV3UsersSelfStatsTimeData = {
    body?: never;
    path?: never;
    query?: {
        unit?: 'days' | 'hours' | 'minutes';
        tz?: string;
        limit?: number;
        start_time?: Date;
        end_time?: Date;
        platform?: string;
        project?: string;
        language?: string;
    };
    url: '/v3/users/self/stats_time';
};

export type GetV3UsersSelfStatsTimeErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3UsersSelfStatsTimeError = GetV3UsersSelfStatsTimeErrors[keyof GetV3UsersSelfStatsTimeErrors];

export type GetV3UsersSelfStatsTimeResponses = {
    /**
     * Stats grouped by time
     */
    200: StatsTimeResponse;
};

export type GetV3UsersSelfStatsTimeResponse = GetV3UsersSelfStatsTimeResponses[keyof GetV3UsersSelfStatsTimeResponses];

export type GetV3UsersSelfStatsData = {
    body?: never;
    path?: never;
    query: {
        by: 'language' | 'workspace' | 'editor' | 'platform';
        unit?: 'days' | 'hours' | 'minutes';
        tz?: string;
        limit?: number;
        start_time?: Date;
        end_time?: Date;
        platform?: string;
        project?: string;
        language?: string;
    };
    url: '/v3/users/self/stats';
};

export type GetV3UsersSelfStatsErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3UsersSelfStatsError = GetV3UsersSelfStatsErrors[keyof GetV3UsersSelfStatsErrors];

export type GetV3UsersSelfStatsResponses = {
    /**
     * Stats data points
     */
    200: StatsResponse;
};

export type GetV3UsersSelfStatsResponse = GetV3UsersSelfStatsResponses[keyof GetV3UsersSelfStatsResponses];

export type GetV3UsersSelfTimeDistributionData = {
    body?: never;
    path?: never;
    query?: {
        start_time?: Date;
        end_time?: Date;
        days?: number;
        tz?: string;
        platform?: string;
        project?: string;
        language?: string;
    };
    url: '/v3/users/self/time-distribution';
};

export type GetV3UsersSelfTimeDistributionErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3UsersSelfTimeDistributionError = GetV3UsersSelfTimeDistributionErrors[keyof GetV3UsersSelfTimeDistributionErrors];

export type GetV3UsersSelfTimeDistributionResponses = {
    /**
     * Time distribution
     */
    200: TimeDistributionResponse;
};

export type GetV3UsersSelfTimeDistributionResponse = GetV3UsersSelfTimeDistributionResponses[keyof GetV3UsersSelfTimeDistributionResponses];

export type GetV3UsersSelfTopLanguagesRankData = {
    body?: never;
    path?: never;
    query?: {
        top_n?: number;
        start_time?: Date;
        end_time?: Date;
        days?: number;
    };
    url: '/v3/users/self/top-languages-rank';
};

export type GetV3UsersSelfTopLanguagesRankErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3UsersSelfTopLanguagesRankError = GetV3UsersSelfTopLanguagesRankErrors[keyof GetV3UsersSelfTopLanguagesRankErrors];

export type GetV3UsersSelfTopLanguagesRankResponses = {
    /**
     * Top-language rankings
     */
    200: UserTopLanguagesRankResponse;
};

export type GetV3UsersSelfTopLanguagesRankResponse = GetV3UsersSelfTopLanguagesRankResponses[keyof GetV3UsersSelfTopLanguagesRankResponses];

export type GetV3UsersSelfTopData = {
    body?: never;
    path?: never;
    query: {
        field: 'language' | 'workspace' | 'editor' | 'platform';
        limit?: number;
        minutes?: number;
        start_time?: Date;
        end_time?: Date;
        languages?: Array<string>;
        workspaces?: Array<string>;
        platforms?: Array<string>;
        editors?: Array<string>;
    };
    url: '/v3/users/self/top';
};

export type GetV3UsersSelfTopErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Insufficient permissions
     */
    403: PyError;
};

export type GetV3UsersSelfTopError = GetV3UsersSelfTopErrors[keyof GetV3UsersSelfTopErrors];

export type GetV3UsersSelfTopResponses = {
    /**
     * Top N items
     */
    200: Array<TopPublic>;
};

export type GetV3UsersSelfTopResponse = GetV3UsersSelfTopResponses[keyof GetV3UsersSelfTopResponses];

export type PostV3UsersSelfUsernameData = {
    body: {
        username: string;
    };
    path?: never;
    query?: never;
    url: '/v3/users/self/username';
};

export type PostV3UsersSelfUsernameErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
    /**
     * Not found
     */
    404: PyError;
};

export type PostV3UsersSelfUsernameError = PostV3UsersSelfUsernameErrors[keyof PostV3UsersSelfUsernameErrors];

export type PostV3UsersSelfUsernameResponses = {
    /**
     * Updated user
     */
    200: UserSelfPublic;
};

export type PostV3UsersSelfUsernameResponse = PostV3UsersSelfUsernameResponses[keyof PostV3UsersSelfUsernameResponses];

export type GetV3UsersSelfWorkspaceData = {
    body?: never;
    path?: never;
    query: {
        project: string;
        days?: number;
        start_time?: Date;
        end_time?: Date;
    };
    url: '/v3/users/self/workspace';
};

export type GetV3UsersSelfWorkspaceErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfWorkspaceError = GetV3UsersSelfWorkspaceErrors[keyof GetV3UsersSelfWorkspaceErrors];

export type GetV3UsersSelfWorkspaceResponses = {
    /**
     * Workspace file activity
     */
    200: Array<WorkspaceFileActivity>;
};

export type GetV3UsersSelfWorkspaceResponse = GetV3UsersSelfWorkspaceResponses[keyof GetV3UsersSelfWorkspaceResponses];

export type GetV3UsersSelfWorkspacesRecentData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        days?: number;
    };
    url: '/v3/users/self/workspaces/recent';
};

export type GetV3UsersSelfWorkspacesRecentErrors = {
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfWorkspacesRecentError = GetV3UsersSelfWorkspacesRecentErrors[keyof GetV3UsersSelfWorkspacesRecentErrors];

export type GetV3UsersSelfWorkspacesRecentResponses = {
    /**
     * Workspace search response
     */
    200: WorkspaceSearchResponse;
};

export type GetV3UsersSelfWorkspacesRecentResponse = GetV3UsersSelfWorkspacesRecentResponses[keyof GetV3UsersSelfWorkspacesRecentResponses];

export type GetV3UsersSelfWorkspacesSearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
    };
    url: '/v3/users/self/workspaces/search';
};

export type GetV3UsersSelfWorkspacesSearchErrors = {
    /**
     * Invalid request
     */
    400: PyError;
    /**
     * Not authenticated
     */
    401: PyError;
};

export type GetV3UsersSelfWorkspacesSearchError = GetV3UsersSelfWorkspacesSearchErrors[keyof GetV3UsersSelfWorkspacesSearchErrors];

export type GetV3UsersSelfWorkspacesSearchResponses = {
    /**
     * Workspace search response
     */
    200: WorkspaceSearchResponse;
};

export type GetV3UsersSelfWorkspacesSearchResponse = GetV3UsersSelfWorkspacesSearchResponses[keyof GetV3UsersSelfWorkspacesSearchResponses];

export type GetV3UsersShieldData = {
    body?: never;
    path?: never;
    query: {
        uid: number;
        /**
         * time = coded minutes; tokens = AI agent tokens consumed. With tokens, `project` matches the agent project name and language/tag/only_hours are ignored.
         */
        metric?: 'time' | 'tokens';
        minutes?: number;
        project?: string;
        language?: string;
        /**
         * Tag name (per-user unique). Rules evaluated in-memory.
         */
        tag?: string;
        only_hours?: boolean;
        /**
         * Left-block color (hex, # optional). Echoed as `labelColor` in the payload — the shields renderer reads it from the JSON, not from its own query string.
         */
        label_color?: string;
    };
    url: '/v3/users/shield';
};

export type GetV3UsersShieldErrors = {
    /**
     * Not found
     */
    404: PyError;
};

export type GetV3UsersShieldError = GetV3UsersShieldErrors[keyof GetV3UsersShieldErrors];

export type GetV3UsersShieldResponses = {
    /**
     * Shield JSON
     */
    200: ShieldResponse;
};

export type GetV3UsersShieldResponse = GetV3UsersShieldResponses[keyof GetV3UsersShieldResponses];
