// This file is auto-generated by @hey-api/openapi-ts

/**
 * CheckoutRequest
 */
export type CheckoutRequest = {
    type: string;
    product: string;
};

/**
 * CheckoutResponse
 */
export type CheckoutResponse = {
    checkoutUrl: string;
    expiresAt: Date;
};

/**
 * EventLogPublic
 */
export type EventLogPublic = {
    eventTime: number;
    language: string;
    project: string;
    relativeFile: string;
    editor: string;
    platform: string;
    absoluteFile: string;
    gitOrigin: string;
    gitBranch: string;
};

/**
 * LeaderboardEntry
 */
export type LeaderboardEntry = {
    user: SrcDtoUserPublic;
    totalMinutes: number;
    rank: number;
};

/**
 * LeaderboardResponse
 */
export type LeaderboardResponse = {
    entries: Array<LeaderboardEntry>;
    totalUsers: number;
    updatedAt: Date;
};

/**
 * PlanStatus
 */
export type PlanStatus = 'active' | 'cancelled' | 'expired' | 'on-trial' | 'paused' | 'past-due' | 'unpaid' | '';

/**
 * PrivacySettingsRequest
 */
export type PrivacySettingsRequest = {
    privacyLevel: string;
    showEmail?: boolean;
    showGithub?: boolean;
};

/**
 * PrivacySettingsResponse
 */
export type PrivacySettingsResponse = {
    privacyLevel: string;
    showEmail: boolean;
    showGithub: boolean;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    id: string;
    name: string;
    description: string;
    price: number;
    currency: string;
    interval?: string | null;
};

/**
 * RootResponse
 */
export type RootResponse = {
    message: string;
    documentUrl: string;
};

/**
 * ShieldResponse
 */
export type ShieldResponse = {
    schemaVersion?: number;
    logoSvg?: string | null;
    label: string;
    message: string;
    color: string;
};

/**
 * StatsData
 */
export type StatsData = {
    duration: number;
    time: string;
    by: string;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    data: Array<StatsData>;
};

/**
 * StatsTimeData
 */
export type StatsTimeData = {
    duration: number;
    time: string;
};

/**
 * StatsTimeResponse
 */
export type StatsTimeResponse = {
    data: Array<StatsTimeData>;
};

/**
 * TimeDistributionData
 */
export type TimeDistributionData = {
    hour: number;
    minute: number;
    count: number;
};

/**
 * TimeDistributionResponse
 */
export type TimeDistributionResponse = {
    data: Array<TimeDistributionData>;
};

/**
 * TokenRefreshResponse
 */
export type TokenRefreshResponse = {
    token: string;
    tokenV1: string;
};

/**
 * TopPublic
 */
export type TopPublic = {
    field: string;
    minutes: number;
};

/**
 * TotalMinutesResponse
 */
export type TotalMinutesResponse = {
    totalMinutes: number;
};

/**
 * UserDeleteResponse
 */
export type UserDeleteResponse = {
    success: boolean;
    message: string;
};

/**
 * UserSelfPublic
 */
export type UserSelfPublic = {
    id: number;
    email?: string | null;
    username: string;
    avatar?: string | null;
    githubId?: number | null;
    bio?: string | null;
    googleId?: string | null;
    plan: string;
    timezone?: string | null;
    uploadToken: string;
    planExpiresAt?: Date | null;
    planStatus?: PlanStatus | null;
    createdAt: Date;
    updatedAt: Date;
};

/**
 * WebhookResponse
 */
export type WebhookResponse = {
    success: boolean;
    message: string;
};

/**
 * WorkspaceFileActivity
 */
export type WorkspaceFileActivity = {
    language: string;
    relativeFile: string;
    gitBranch: string;
    createdAt: Date;
};

/**
 * WorkspaceSearchResponse
 */
export type WorkspaceSearchResponse = {
    results: Array<WorkspaceSearchResult>;
    totalResults: number;
};

/**
 * WorkspaceSearchResult
 */
export type WorkspaceSearchResult = {
    workspaceName: string;
};

/**
 * YearlyReportDataPublic
 */
export type YearlyReportDataPublic = {
    topLanguages: Array<TopPublic>;
    hourlyDistribution: Array<TopPublic>;
    dailyDistribution: Array<TopPublic>;
};

/**
 * UserPublic
 */
export type DtoUserPublic = {
    id: number;
    email?: string | null;
    username: string;
    avatar?: string | null;
    githubId?: number | null;
    bio?: string | null;
    googleId?: string | null;
    plan: string;
    timezone?: string | null;
    createdAt: Date;
    updatedAt: Date;
};

/**
 * UserPublic
 */
export type SrcDtoUserPublic = {
    id: number;
    email?: string | null;
    username: string;
    avatar?: string | null;
    githubId?: number | null;
    bio?: string | null;
    googleId?: string | null;
    plan: string;
    timezone?: string | null;
    createdAt: Date;
    updatedAt: Date;
};

export type V3GetRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3';
};

export type V3GetRootResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: RootResponse;
};

export type V3GetRootResponse = V3GetRootResponses[keyof V3GetRootResponses];

export type V3GetTotalMinutesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/total-minutes';
};

export type V3GetTotalMinutesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TotalMinutesResponse;
};

export type V3GetTotalMinutesResponse = V3GetTotalMinutesResponses[keyof V3GetTotalMinutesResponses];

export type V3GithubCallbackData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Authorization code from GitHub
         */
        code: string;
    };
    url: '/v3/auth/github';
};

export type V3GithubCallbackErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GithubCallbackError = V3GithubCallbackErrors[keyof V3GithubCallbackErrors];

export type V3GithubCallbackResponses = {
    /**
     * Redirect Response
     */
    200: unknown;
};

export type V3GoogleAuthData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/v3/auth/google';
};

export type V3GoogleAuthErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GoogleAuthError = V3GoogleAuthErrors[keyof V3GoogleAuthErrors];

export type V3GoogleAuthResponses = {
    /**
     * Redirect Response
     */
    201: unknown;
};

export type V3LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/logout';
};

export type V3LogoutResponses = {
    /**
     * Document created, URL follows
     */
    201: unknown;
};

export type V3RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/refresh-token';
};

export type V3RefreshTokenResponses = {
    /**
     * Document created, URL follows
     */
    201: TokenRefreshResponse;
};

export type V3RefreshTokenResponse = V3RefreshTokenResponses[keyof V3RefreshTokenResponses];

export type V3DeleteUserAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self';
};

export type V3DeleteUserAccountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserDeleteResponse;
};

export type V3DeleteUserAccountResponse = V3DeleteUserAccountResponses[keyof V3DeleteUserAccountResponses];

export type V3GetUserSelfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self';
};

export type V3GetUserSelfResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserSelfPublic;
};

export type V3GetUserSelfResponse = V3GetUserSelfResponses[keyof V3GetUserSelfResponses];

export type V3DeleteUserDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self/data';
};

export type V3DeleteUserDataResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserDeleteResponse;
};

export type V3DeleteUserDataResponse = V3DeleteUserDataResponses[keyof V3DeleteUserDataResponses];

export type V3ExportUserDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self/export';
};

export type V3ExportUserDataResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type V3ExportUserDataResponse = V3ExportUserDataResponses[keyof V3ExportUserDataResponses];

export type V3GetPrivacySettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/users/self/privacy';
};

export type V3GetPrivacySettingsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PrivacySettingsResponse;
};

export type V3GetPrivacySettingsResponse = V3GetPrivacySettingsResponses[keyof V3GetPrivacySettingsResponses];

export type V3UpdatePrivacySettingsData = {
    body: PrivacySettingsRequest;
    path?: never;
    query?: never;
    url: '/v3/users/self/privacy';
};

export type V3UpdatePrivacySettingsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3UpdatePrivacySettingsError = V3UpdatePrivacySettingsErrors[keyof V3UpdatePrivacySettingsErrors];

export type V3UpdatePrivacySettingsResponses = {
    /**
     * Document created, URL follows
     */
    201: PrivacySettingsResponse;
};

export type V3UpdatePrivacySettingsResponse = V3UpdatePrivacySettingsResponses[keyof V3UpdatePrivacySettingsResponses];

export type V3GetTimeDistributionData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
        tz?: string | null;
        platform?: string | null;
        project?: string | null;
        language?: string | null;
    };
    url: '/v3/users/self/time-distribution';
};

export type V3GetTimeDistributionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GetTimeDistributionError = V3GetTimeDistributionErrors[keyof V3GetTimeDistributionErrors];

export type V3GetTimeDistributionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TimeDistributionResponse;
};

export type V3GetTimeDistributionResponse = V3GetTimeDistributionResponses[keyof V3GetTimeDistributionResponses];

export type V3GetUserByUserIdData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/v3/users/{user_id}';
};

export type V3GetUserByUserIdErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GetUserByUserIdError = V3GetUserByUserIdErrors[keyof V3GetUserByUserIdErrors];

export type V3GetUserByUserIdResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DtoUserPublic;
};

export type V3GetUserByUserIdResponse = V3GetUserByUserIdResponses[keyof V3GetUserByUserIdResponses];

export type V3GetUserShieldData = {
    body?: never;
    path?: never;
    query: {
        uid: number;
        minutes?: number | string | null;
        project?: string | null;
        language?: string | null;
        only_hours?: boolean;
    };
    url: '/v3/users/shield';
};

export type V3GetUserShieldErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GetUserShieldError = V3GetUserShieldErrors[keyof V3GetUserShieldErrors];

export type V3GetUserShieldResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ShieldResponse;
};

export type V3GetUserShieldResponse = V3GetUserShieldResponses[keyof V3GetUserShieldResponses];

export type V3GetWorkspaceFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project/workspace name to filter by
         */
        project: string;
        /**
         * Number of days to look back
         */
        days?: number | null;
    };
    url: '/v3/users/self/workspace';
};

export type V3GetWorkspaceFilesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GetWorkspaceFilesError = V3GetWorkspaceFilesErrors[keyof V3GetWorkspaceFilesErrors];

export type V3GetWorkspaceFilesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<WorkspaceFileActivity>;
};

export type V3GetWorkspaceFilesResponse = V3GetWorkspaceFilesResponses[keyof V3GetWorkspaceFilesResponses];

export type V3ListSelfLatestLogsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/v3/users/self/latest-logs';
};

export type V3ListSelfLatestLogsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3ListSelfLatestLogsError = V3ListSelfLatestLogsErrors[keyof V3ListSelfLatestLogsErrors];

export type V3ListSelfLatestLogsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<EventLogPublic>;
};

export type V3ListSelfLatestLogsResponse = V3ListSelfLatestLogsResponses[keyof V3ListSelfLatestLogsResponses];

export type V3ListSelfStatsData = {
    body?: never;
    path?: never;
    query: {
        by: 'language' | 'workspace' | 'editor' | 'platform';
        unit?: 'days' | 'hours' | 'minutes';
        tz?: string | null;
        limit?: number;
        platform?: string | null;
        project?: string | null;
        language?: string | null;
    };
    url: '/v3/users/self/stats';
};

export type V3ListSelfStatsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3ListSelfStatsError = V3ListSelfStatsErrors[keyof V3ListSelfStatsErrors];

export type V3ListSelfStatsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: StatsResponse;
};

export type V3ListSelfStatsResponse = V3ListSelfStatsResponses[keyof V3ListSelfStatsResponses];

export type V3ListSelfStatsTimeData = {
    body?: never;
    path?: never;
    query?: {
        unit?: 'days' | 'hours' | 'minutes';
        tz?: string | null;
        limit?: number;
        platform?: string | null;
        project?: string | null;
        language?: string | null;
    };
    url: '/v3/users/self/stats_time';
};

export type V3ListSelfStatsTimeErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3ListSelfStatsTimeError = V3ListSelfStatsTimeErrors[keyof V3ListSelfStatsTimeErrors];

export type V3ListSelfStatsTimeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: StatsTimeResponse;
};

export type V3ListSelfStatsTimeResponse = V3ListSelfStatsTimeResponses[keyof V3ListSelfStatsTimeResponses];

export type V3ListSelfTopData = {
    body?: never;
    path?: never;
    query: {
        field: 'language' | 'workspace' | 'editor' | 'platform';
        limit?: number | null;
        minutes?: number | null;
        languages?: Array<string> | null;
        workspaces?: Array<string> | null;
        platforms?: Array<string> | null;
        editors?: Array<string> | null;
    };
    url: '/v3/users/self/top';
};

export type V3ListSelfTopErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3ListSelfTopError = V3ListSelfTopErrors[keyof V3ListSelfTopErrors];

export type V3ListSelfTopResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<TopPublic>;
};

export type V3ListSelfTopResponse = V3ListSelfTopResponses[keyof V3ListSelfTopResponses];

export type V3SearchWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search query for workspace names
         */
        q?: string;
        /**
         * Number of results to return
         */
        limit?: number;
    };
    url: '/v3/users/self/workspaces/search';
};

export type V3SearchWorkspacesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3SearchWorkspacesError = V3SearchWorkspacesErrors[keyof V3SearchWorkspacesErrors];

export type V3SearchWorkspacesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: WorkspaceSearchResponse;
};

export type V3SearchWorkspacesResponse = V3SearchWorkspacesResponses[keyof V3SearchWorkspacesResponses];

export type V3GetYearlyReportDataData = {
    body?: never;
    path?: never;
    query: {
        user_id: number;
        /**
         * Year to get report for
         */
        year?: '2024';
        /**
         * Timezone for the report
         */
        timezone?: string;
    };
    url: '/v3/logs/yearly-report-data';
};

export type V3GetYearlyReportDataErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GetYearlyReportDataError = V3GetYearlyReportDataErrors[keyof V3GetYearlyReportDataErrors];

export type V3GetYearlyReportDataResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: YearlyReportDataPublic;
};

export type V3GetYearlyReportDataResponse = V3GetYearlyReportDataResponses[keyof V3GetYearlyReportDataResponses];

export type V3CreateCheckoutData = {
    body: CheckoutRequest;
    path?: never;
    query?: never;
    url: '/v3/payments/checkout';
};

export type V3CreateCheckoutErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3CreateCheckoutError = V3CreateCheckoutErrors[keyof V3CreateCheckoutErrors];

export type V3CreateCheckoutResponses = {
    /**
     * Document created, URL follows
     */
    201: CheckoutResponse;
};

export type V3CreateCheckoutResponse = V3CreateCheckoutResponses[keyof V3CreateCheckoutResponses];

export type V3GetProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/payments/products';
};

export type V3GetProductsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ProductPublic>;
};

export type V3GetProductsResponse = V3GetProductsResponses[keyof V3GetProductsResponses];

export type V3HandleLemonsqueezyWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/payments/webhooks/lemonsqueezy';
};

export type V3HandleLemonsqueezyWebhookResponses = {
    /**
     * Document created, URL follows
     */
    201: WebhookResponse;
};

export type V3HandleLemonsqueezyWebhookResponse = V3HandleLemonsqueezyWebhookResponses[keyof V3HandleLemonsqueezyWebhookResponses];

export type V3GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of entries to return
         */
        limit?: number;
        /**
         * Number of days to look back, null for all time
         */
        days?: number | null;
    };
    url: '/v3/public/leaderboard';
};

export type V3GetLeaderboardErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type V3GetLeaderboardError = V3GetLeaderboardErrors[keyof V3GetLeaderboardErrors];

export type V3GetLeaderboardResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: LeaderboardResponse;
};

export type V3GetLeaderboardResponse = V3GetLeaderboardResponses[keyof V3GetLeaderboardResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};